// Copyright Epic Games, Inc. All Rights Reserved.
#pragma once

// Generated by tools/gen_verse_api.py from gdextension/extension_api.json
// (Godot Engine v4.7.stable.official). Do not edit by hand.
//
// The shape of each Godot math type as Verse declares it, for the host's marshalling: which fields
// a struct has, in order, and which of them are structs of their own. Generated from the same
// MATH_LAYOUT that emits the Verse structs and their packers, so the two cannot drift -- a value
// built here with the fields of a type it is not would be read back as plausible nonsense.
//
// Scalar fields carry NestedTag 0. A nested one carries the tag of the struct it holds, which is
// its entry in MathLayouts below.

namespace verse_math {

struct field
{
	const char *name;
	// 0 for a scalar; otherwise the vh_variant_tag of the struct this field holds.
	int nested_tag;
	// A scalar field holding an integer rather than a float -- the integer vectors, whose
	// components stop being exact as doubles above 2^53.
	bool is_int;
};

struct layout
{
	const char *verse_name;
	int variant_tag;
	// The packed array Godot has for this struct, which an array of them crosses as. 0 for none.
	int packed_array_tag;
	const field *fields;
	int field_count;
};

inline constexpr field vector2_fields[] = {
	{"X", 0, false},
	{"Y", 0, false},
};

inline constexpr field vector2i_fields[] = {
	{"X", 0, true},
	{"Y", 0, true},
};

inline constexpr field vector3_fields[] = {
	{"X", 0, false},
	{"Y", 0, false},
	{"Z", 0, false},
};

inline constexpr field vector3i_fields[] = {
	{"X", 0, true},
	{"Y", 0, true},
	{"Z", 0, true},
};

inline constexpr field vector4_fields[] = {
	{"X", 0, false},
	{"Y", 0, false},
	{"Z", 0, false},
	{"W", 0, false},
};

inline constexpr field vector4i_fields[] = {
	{"X", 0, true},
	{"Y", 0, true},
	{"Z", 0, true},
	{"W", 0, true},
};

inline constexpr field rect2_fields[] = {
	{"Position", VH_VARIANT_VECTOR2, false},
	{"Size", VH_VARIANT_VECTOR2, false},
};

inline constexpr field rect2i_fields[] = {
	{"Position", VH_VARIANT_VECTOR2I, false},
	{"Size", VH_VARIANT_VECTOR2I, false},
};

inline constexpr field plane_fields[] = {
	{"Normal", VH_VARIANT_VECTOR3, false},
	{"D", 0, false},
};

inline constexpr field quaternion_fields[] = {
	{"X", 0, false},
	{"Y", 0, false},
	{"Z", 0, false},
	{"W", 0, false},
};

inline constexpr field aabb_fields[] = {
	{"Position", VH_VARIANT_VECTOR3, false},
	{"Size", VH_VARIANT_VECTOR3, false},
};

inline constexpr field basis_fields[] = {
	{"X", VH_VARIANT_VECTOR3, false},
	{"Y", VH_VARIANT_VECTOR3, false},
	{"Z", VH_VARIANT_VECTOR3, false},
};

inline constexpr field transform2d_fields[] = {
	{"X", VH_VARIANT_VECTOR2, false},
	{"Y", VH_VARIANT_VECTOR2, false},
	{"Origin", VH_VARIANT_VECTOR2, false},
};

inline constexpr field transform3d_fields[] = {
	{"Basis", VH_VARIANT_BASIS, false},
	{"Origin", VH_VARIANT_VECTOR3, false},
};

inline constexpr field projection_fields[] = {
	{"X", VH_VARIANT_VECTOR4, false},
	{"Y", VH_VARIANT_VECTOR4, false},
	{"Z", VH_VARIANT_VECTOR4, false},
	{"W", VH_VARIANT_VECTOR4, false},
};

inline constexpr field color_fields[] = {
	{"R", 0, false},
	{"G", 0, false},
	{"B", 0, false},
	{"A", 0, false},
};

inline constexpr layout layouts[] = {
	{"vector2", VH_VARIANT_VECTOR2, VH_VARIANT_PACKED_VECTOR2_ARRAY, vector2_fields, 2},
	{"vector2i", VH_VARIANT_VECTOR2I, 0, vector2i_fields, 2},
	{"vector3", VH_VARIANT_VECTOR3, VH_VARIANT_PACKED_VECTOR3_ARRAY, vector3_fields, 3},
	{"vector3i", VH_VARIANT_VECTOR3I, 0, vector3i_fields, 3},
	{"vector4", VH_VARIANT_VECTOR4, VH_VARIANT_PACKED_VECTOR4_ARRAY, vector4_fields, 4},
	{"vector4i", VH_VARIANT_VECTOR4I, 0, vector4i_fields, 4},
	{"rect2", VH_VARIANT_RECT2, 0, rect2_fields, 2},
	{"rect2i", VH_VARIANT_RECT2I, 0, rect2i_fields, 2},
	{"plane", VH_VARIANT_PLANE, 0, plane_fields, 2},
	{"quaternion", VH_VARIANT_QUATERNION, 0, quaternion_fields, 4},
	{"aabb", VH_VARIANT_AABB, 0, aabb_fields, 2},
	{"basis", VH_VARIANT_BASIS, 0, basis_fields, 3},
	{"transform2d", VH_VARIANT_TRANSFORM2D, 0, transform2d_fields, 3},
	{"transform3d", VH_VARIANT_TRANSFORM3D, 0, transform3d_fields, 2},
	{"projection", VH_VARIANT_PROJECTION, 0, projection_fields, 4},
	{"color", VH_VARIANT_COLOR, VH_VARIANT_PACKED_COLOR_ARRAY, color_fields, 4},
};

// The Verse classes that wrap a reference id rather than carrying a value, and the Godot type each
// names. The host needs this to report a parameter's or a result's type across the ABI: without
// it Godot is told the argument is Nil and refuses to pass one.
struct reference_type
{
	const char *verse_name;
	int variant_tag;
};

inline constexpr reference_type reference_types[] = {
	{"godot_array", VH_VARIANT_ARRAY},
	{"dictionary", VH_VARIANT_DICTIONARY},
	{"callable", VH_VARIANT_CALLABLE},
	{"signal_ref", VH_VARIANT_SIGNAL},
};

} // namespace verse_math
