// Copyright Epic Games, Inc. All Rights Reserved.
#pragma once

// Generated by tools/gen_vbc_writer.py from docs/web-vm/ops.json. Do not edit by hand.
//
// VbcEncodeOp calls one encoder method per operand the schema lists for the op, in the schema's
// order, skipping cache operands. The method is chosen by the operand's kind, then `Range` when
// it is variadic and an `Opt` prefix when it is optional; every call also carries the role.

#include "VerseVM/VVMBytecodesAndCaptures.h"

namespace GodotVerse::Vbc {

inline constexpr const char* OpSchemaDigest = "0c249c8bd5daf1537da5b945fcf2a62b84d2348b51501b524ac616ee13716c9e";
inline constexpr uint32 OpCount = 114;

enum class ERole : uint8
{
	Use,
	Immediate,
	UnifyDef,
	ClobberDef,
	Const,
	Jump,
};

static_assert(static_cast<uint32>(Verse::EOpcode::OpcodeCount) == 114, "the engine's op set is not the one ops.json describes");
static_assert(static_cast<uint32>(Verse::EOpcode::Add) == 0);
static_assert(static_cast<uint32>(Verse::EOpcode::Sub) == 1);
static_assert(static_cast<uint32>(Verse::EOpcode::Mul) == 2);
static_assert(static_cast<uint32>(Verse::EOpcode::Div) == 3);
static_assert(static_cast<uint32>(Verse::EOpcode::Mod) == 4);
static_assert(static_cast<uint32>(Verse::EOpcode::CanFastAppendToArrayFastFail) == 5);
static_assert(static_cast<uint32>(Verse::EOpcode::FastAppendToArray) == 6);
static_assert(static_cast<uint32>(Verse::EOpcode::MutableAdd) == 7);
static_assert(static_cast<uint32>(Verse::EOpcode::Neg) == 8);
static_assert(static_cast<uint32>(Verse::EOpcode::Query) == 9);
static_assert(static_cast<uint32>(Verse::EOpcode::Err) == 10);
static_assert(static_cast<uint32>(Verse::EOpcode::Tracepoint) == 11);
static_assert(static_cast<uint32>(Verse::EOpcode::Move) == 12);
static_assert(static_cast<uint32>(Verse::EOpcode::MoveTrailed) == 13);
static_assert(static_cast<uint32>(Verse::EOpcode::MoveNonComparable) == 14);
static_assert(static_cast<uint32>(Verse::EOpcode::Reset) == 15);
static_assert(static_cast<uint32>(Verse::EOpcode::ResetNonTrailed) == 16);
static_assert(static_cast<uint32>(Verse::EOpcode::Jump) == 17);
static_assert(static_cast<uint32>(Verse::EOpcode::JumpIfInitialized) == 18);
static_assert(static_cast<uint32>(Verse::EOpcode::Switch) == 19);
static_assert(static_cast<uint32>(Verse::EOpcode::LtFastFail) == 20);
static_assert(static_cast<uint32>(Verse::EOpcode::LteFastFail) == 21);
static_assert(static_cast<uint32>(Verse::EOpcode::GtFastFail) == 22);
static_assert(static_cast<uint32>(Verse::EOpcode::GteFastFail) == 23);
static_assert(static_cast<uint32>(Verse::EOpcode::EqFastFail) == 24);
static_assert(static_cast<uint32>(Verse::EOpcode::NeqFastFail) == 25);
static_assert(static_cast<uint32>(Verse::EOpcode::ArrayIndexFastFail) == 26);
static_assert(static_cast<uint32>(Verse::EOpcode::TypeCastFastFail) == 27);
static_assert(static_cast<uint32>(Verse::EOpcode::QueryFastFail) == 28);
static_assert(static_cast<uint32>(Verse::EOpcode::EndFastFailureContext) == 29);
static_assert(static_cast<uint32>(Verse::EOpcode::BeginFailureContext) == 30);
static_assert(static_cast<uint32>(Verse::EOpcode::EndFailureContext) == 31);
static_assert(static_cast<uint32>(Verse::EOpcode::SelfTask) == 32);
static_assert(static_cast<uint32>(Verse::EOpcode::BeginTask) == 33);
static_assert(static_cast<uint32>(Verse::EOpcode::CallTask) == 34);
static_assert(static_cast<uint32>(Verse::EOpcode::EndTask) == 35);
static_assert(static_cast<uint32>(Verse::EOpcode::BeginAwait) == 36);
static_assert(static_cast<uint32>(Verse::EOpcode::AwaitSuccess) == 37);
static_assert(static_cast<uint32>(Verse::EOpcode::EndAwait) == 38);
static_assert(static_cast<uint32>(Verse::EOpcode::BeginBatch) == 39);
static_assert(static_cast<uint32>(Verse::EOpcode::EndBatch) == 40);
static_assert(static_cast<uint32>(Verse::EOpcode::Yield) == 41);
static_assert(static_cast<uint32>(Verse::EOpcode::NewSemaphore) == 42);
static_assert(static_cast<uint32>(Verse::EOpcode::WaitSemaphore) == 43);
static_assert(static_cast<uint32>(Verse::EOpcode::Call) == 44);
static_assert(static_cast<uint32>(Verse::EOpcode::CallWithSelf) == 45);
static_assert(static_cast<uint32>(Verse::EOpcode::Return) == 46);
static_assert(static_cast<uint32>(Verse::EOpcode::ReturnTrailed) == 47);
static_assert(static_cast<uint32>(Verse::EOpcode::ResumeUnwind) == 48);
static_assert(static_cast<uint32>(Verse::EOpcode::NewRef) == 49);
static_assert(static_cast<uint32>(Verse::EOpcode::NewPersistentOrSessionWeakMapRef) == 50);
static_assert(static_cast<uint32>(Verse::EOpcode::RefGet) == 51);
static_assert(static_cast<uint32>(Verse::EOpcode::RefSet) == 52);
static_assert(static_cast<uint32>(Verse::EOpcode::RefSetLive) == 53);
static_assert(static_cast<uint32>(Verse::EOpcode::RefCallDomain) == 54);
static_assert(static_cast<uint32>(Verse::EOpcode::Freeze) == 55);
static_assert(static_cast<uint32>(Verse::EOpcode::FreezeIfAccessor) == 56);
static_assert(static_cast<uint32>(Verse::EOpcode::Melt) == 57);
static_assert(static_cast<uint32>(Verse::EOpcode::Length) == 58);
static_assert(static_cast<uint32>(Verse::EOpcode::LengthWithEffects) == 59);
static_assert(static_cast<uint32>(Verse::EOpcode::CallSet) == 60);
static_assert(static_cast<uint32>(Verse::EOpcode::CallSetLive) == 61);
static_assert(static_cast<uint32>(Verse::EOpcode::NewArray) == 62);
static_assert(static_cast<uint32>(Verse::EOpcode::NewMutableArray) == 63);
static_assert(static_cast<uint32>(Verse::EOpcode::NewMutableArrayWithCapacity) == 64);
static_assert(static_cast<uint32>(Verse::EOpcode::ArrayAdd) == 65);
static_assert(static_cast<uint32>(Verse::EOpcode::InPlaceMakeImmutable) == 66);
static_assert(static_cast<uint32>(Verse::EOpcode::NewOption) == 67);
static_assert(static_cast<uint32>(Verse::EOpcode::NewUnionVariant) == 68);
static_assert(static_cast<uint32>(Verse::EOpcode::GetUnionVariantPayload) == 69);
static_assert(static_cast<uint32>(Verse::EOpcode::GetUnionVariantTag) == 70);
static_assert(static_cast<uint32>(Verse::EOpcode::NewMap) == 71);
static_assert(static_cast<uint32>(Verse::EOpcode::MapKey) == 72);
static_assert(static_cast<uint32>(Verse::EOpcode::MapValue) == 73);
static_assert(static_cast<uint32>(Verse::EOpcode::NewClass) == 74);
static_assert(static_cast<uint32>(Verse::EOpcode::BindNativeClass) == 75);
static_assert(static_cast<uint32>(Verse::EOpcode::ConstructNativeDefaultObject) == 76);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadImport) == 77);
static_assert(static_cast<uint32>(Verse::EOpcode::JumpIfDefaultSubObject) == 78);
static_assert(static_cast<uint32>(Verse::EOpcode::BeginModule) == 79);
static_assert(static_cast<uint32>(Verse::EOpcode::EndModule) == 80);
static_assert(static_cast<uint32>(Verse::EOpcode::EndModuleData) == 81);
static_assert(static_cast<uint32>(Verse::EOpcode::NewObject) == 82);
static_assert(static_cast<uint32>(Verse::EOpcode::NewObjectICClass) == 83);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadField) == 84);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadFieldICOffset) == 85);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadFieldICConstant) == 86);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadFieldICFunction) == 87);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadFieldICNativeFunction) == 88);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadFieldICAccessor) == 89);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadFieldFromSuper) == 90);
static_assert(static_cast<uint32>(Verse::EOpcode::CreateField) == 91);
static_assert(static_cast<uint32>(Verse::EOpcode::CreateFieldICValueObjectConstant) == 92);
static_assert(static_cast<uint32>(Verse::EOpcode::CreateFieldICValueObjectField) == 93);
static_assert(static_cast<uint32>(Verse::EOpcode::CreateFieldICNativeStruct) == 94);
static_assert(static_cast<uint32>(Verse::EOpcode::CreateFieldICUObject) == 95);
static_assert(static_cast<uint32>(Verse::EOpcode::UnifyField) == 96);
static_assert(static_cast<uint32>(Verse::EOpcode::InitializeVar) == 97);
static_assert(static_cast<uint32>(Verse::EOpcode::SetField) == 98);
static_assert(static_cast<uint32>(Verse::EOpcode::SetFieldLive) == 99);
static_assert(static_cast<uint32>(Verse::EOpcode::UnifyNativeObject) == 100);
static_assert(static_cast<uint32>(Verse::EOpcode::UnwrapNativeConstructorWrapper) == 101);
static_assert(static_cast<uint32>(Verse::EOpcode::NewScope) == 102);
static_assert(static_cast<uint32>(Verse::EOpcode::NewFunction) == 103);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadParentScope) == 104);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadCapture) == 105);
static_assert(static_cast<uint32>(Verse::EOpcode::BeginProfileBlock) == 106);
static_assert(static_cast<uint32>(Verse::EOpcode::EndProfileBlock) == 107);
static_assert(static_cast<uint32>(Verse::EOpcode::LoadConstructor) == 108);
static_assert(static_cast<uint32>(Verse::EOpcode::Neq) == 109);
static_assert(static_cast<uint32>(Verse::EOpcode::Lt) == 110);
static_assert(static_cast<uint32>(Verse::EOpcode::Lte) == 111);
static_assert(static_cast<uint32>(Verse::EOpcode::Gt) == 112);
static_assert(static_cast<uint32>(Verse::EOpcode::Gte) == 113);

inline constexpr const char* OpNames[OpCount] = {
	"Add",
	"Sub",
	"Mul",
	"Div",
	"Mod",
	"CanFastAppendToArrayFastFail",
	"FastAppendToArray",
	"MutableAdd",
	"Neg",
	"Query",
	"Err",
	"Tracepoint",
	"Move",
	"MoveTrailed",
	"MoveNonComparable",
	"Reset",
	"ResetNonTrailed",
	"Jump",
	"JumpIfInitialized",
	"Switch",
	"LtFastFail",
	"LteFastFail",
	"GtFastFail",
	"GteFastFail",
	"EqFastFail",
	"NeqFastFail",
	"ArrayIndexFastFail",
	"TypeCastFastFail",
	"QueryFastFail",
	"EndFastFailureContext",
	"BeginFailureContext",
	"EndFailureContext",
	"SelfTask",
	"BeginTask",
	"CallTask",
	"EndTask",
	"BeginAwait",
	"AwaitSuccess",
	"EndAwait",
	"BeginBatch",
	"EndBatch",
	"Yield",
	"NewSemaphore",
	"WaitSemaphore",
	"Call",
	"CallWithSelf",
	"Return",
	"ReturnTrailed",
	"ResumeUnwind",
	"NewRef",
	"NewPersistentOrSessionWeakMapRef",
	"RefGet",
	"RefSet",
	"RefSetLive",
	"RefCallDomain",
	"Freeze",
	"FreezeIfAccessor",
	"Melt",
	"Length",
	"LengthWithEffects",
	"CallSet",
	"CallSetLive",
	"NewArray",
	"NewMutableArray",
	"NewMutableArrayWithCapacity",
	"ArrayAdd",
	"InPlaceMakeImmutable",
	"NewOption",
	"NewUnionVariant",
	"GetUnionVariantPayload",
	"GetUnionVariantTag",
	"NewMap",
	"MapKey",
	"MapValue",
	"NewClass",
	"BindNativeClass",
	"ConstructNativeDefaultObject",
	"LoadImport",
	"JumpIfDefaultSubObject",
	"BeginModule",
	"EndModule",
	"EndModuleData",
	"NewObject",
	"NewObjectICClass",
	"LoadField",
	"LoadFieldICOffset",
	"LoadFieldICConstant",
	"LoadFieldICFunction",
	"LoadFieldICNativeFunction",
	"LoadFieldICAccessor",
	"LoadFieldFromSuper",
	"CreateField",
	"CreateFieldICValueObjectConstant",
	"CreateFieldICValueObjectField",
	"CreateFieldICNativeStruct",
	"CreateFieldICUObject",
	"UnifyField",
	"InitializeVar",
	"SetField",
	"SetFieldLive",
	"UnifyNativeObject",
	"UnwrapNativeConstructorWrapper",
	"NewScope",
	"NewFunction",
	"LoadParentScope",
	"LoadCapture",
	"BeginProfileBlock",
	"EndProfileBlock",
	"LoadConstructor",
	"Neq",
	"Lt",
	"Lte",
	"Gt",
	"Gte",
};

inline constexpr bool OpMayPark[OpCount] = {
	true, // Add
	true, // Sub
	true, // Mul
	true, // Div
	true, // Mod
	true, // CanFastAppendToArrayFastFail
	true, // FastAppendToArray
	true, // MutableAdd
	true, // Neg
	true, // Query
	false, // Err
	false, // Tracepoint
	false, // Move
	false, // MoveTrailed
	false, // MoveNonComparable
	false, // Reset
	false, // ResetNonTrailed
	false, // Jump
	false, // JumpIfInitialized
	false, // Switch
	true, // LtFastFail
	true, // LteFastFail
	true, // GtFastFail
	true, // GteFastFail
	true, // EqFastFail
	true, // NeqFastFail
	true, // ArrayIndexFastFail
	true, // TypeCastFastFail
	true, // QueryFastFail
	false, // EndFastFailureContext
	false, // BeginFailureContext
	false, // EndFailureContext
	false, // SelfTask
	false, // BeginTask
	false, // CallTask
	false, // EndTask
	true, // BeginAwait
	true, // AwaitSuccess
	true, // EndAwait
	true, // BeginBatch
	true, // EndBatch
	false, // Yield
	false, // NewSemaphore
	false, // WaitSemaphore
	true, // Call
	true, // CallWithSelf
	false, // Return
	false, // ReturnTrailed
	false, // ResumeUnwind
	false, // NewRef
	false, // NewPersistentOrSessionWeakMapRef
	true, // RefGet
	true, // RefSet
	true, // RefSetLive
	true, // RefCallDomain
	true, // Freeze
	true, // FreezeIfAccessor
	true, // Melt
	true, // Length
	true, // LengthWithEffects
	true, // CallSet
	true, // CallSetLive
	true, // NewArray
	true, // NewMutableArray
	true, // NewMutableArrayWithCapacity
	true, // ArrayAdd
	true, // InPlaceMakeImmutable
	true, // NewOption
	true, // NewUnionVariant
	true, // GetUnionVariantPayload
	true, // GetUnionVariantTag
	true, // NewMap
	true, // MapKey
	true, // MapValue
	true, // NewClass
	true, // BindNativeClass
	false, // ConstructNativeDefaultObject
	false, // LoadImport
	false, // JumpIfDefaultSubObject
	false, // BeginModule
	false, // EndModule
	true, // EndModuleData
	true, // NewObject
	true, // NewObjectICClass
	true, // LoadField
	true, // LoadFieldICOffset
	true, // LoadFieldICConstant
	true, // LoadFieldICFunction
	true, // LoadFieldICNativeFunction
	true, // LoadFieldICAccessor
	true, // LoadFieldFromSuper
	true, // CreateField
	true, // CreateFieldICValueObjectConstant
	true, // CreateFieldICValueObjectField
	true, // CreateFieldICNativeStruct
	true, // CreateFieldICUObject
	true, // UnifyField
	true, // InitializeVar
	true, // SetField
	true, // SetFieldLive
	true, // UnifyNativeObject
	true, // UnwrapNativeConstructorWrapper
	true, // NewScope
	true, // NewFunction
	true, // LoadParentScope
	true, // LoadCapture
	true, // BeginProfileBlock
	true, // EndProfileBlock
	true, // LoadConstructor
	true, // Neq
	true, // Lt
	true, // Lte
	true, // Gt
	true, // Gte
};

/// The op's size in the stream, which is where the next op starts. Zero for an opcode the
/// schema does not have.
AUTORTFM_DISABLE inline uint32 OpSize(const Verse::FOp& Op)
{
	switch (Op.Opcode)
	{
		case Verse::EOpcode::Add:
			return sizeof(Verse::FOpAdd);
		case Verse::EOpcode::Sub:
			return sizeof(Verse::FOpSub);
		case Verse::EOpcode::Mul:
			return sizeof(Verse::FOpMul);
		case Verse::EOpcode::Div:
			return sizeof(Verse::FOpDiv);
		case Verse::EOpcode::Mod:
			return sizeof(Verse::FOpMod);
		case Verse::EOpcode::CanFastAppendToArrayFastFail:
			return sizeof(Verse::FOpCanFastAppendToArrayFastFail);
		case Verse::EOpcode::FastAppendToArray:
			return sizeof(Verse::FOpFastAppendToArray);
		case Verse::EOpcode::MutableAdd:
			return sizeof(Verse::FOpMutableAdd);
		case Verse::EOpcode::Neg:
			return sizeof(Verse::FOpNeg);
		case Verse::EOpcode::Query:
			return sizeof(Verse::FOpQuery);
		case Verse::EOpcode::Err:
			return sizeof(Verse::FOpErr);
		case Verse::EOpcode::Tracepoint:
			return sizeof(Verse::FOpTracepoint);
		case Verse::EOpcode::Move:
			return sizeof(Verse::FOpMove);
		case Verse::EOpcode::MoveTrailed:
			return sizeof(Verse::FOpMoveTrailed);
		case Verse::EOpcode::MoveNonComparable:
			return sizeof(Verse::FOpMoveNonComparable);
		case Verse::EOpcode::Reset:
			return sizeof(Verse::FOpReset);
		case Verse::EOpcode::ResetNonTrailed:
			return sizeof(Verse::FOpResetNonTrailed);
		case Verse::EOpcode::Jump:
			return sizeof(Verse::FOpJump);
		case Verse::EOpcode::JumpIfInitialized:
			return sizeof(Verse::FOpJumpIfInitialized);
		case Verse::EOpcode::Switch:
			return sizeof(Verse::FOpSwitch);
		case Verse::EOpcode::LtFastFail:
			return sizeof(Verse::FOpLtFastFail);
		case Verse::EOpcode::LteFastFail:
			return sizeof(Verse::FOpLteFastFail);
		case Verse::EOpcode::GtFastFail:
			return sizeof(Verse::FOpGtFastFail);
		case Verse::EOpcode::GteFastFail:
			return sizeof(Verse::FOpGteFastFail);
		case Verse::EOpcode::EqFastFail:
			return sizeof(Verse::FOpEqFastFail);
		case Verse::EOpcode::NeqFastFail:
			return sizeof(Verse::FOpNeqFastFail);
		case Verse::EOpcode::ArrayIndexFastFail:
			return sizeof(Verse::FOpArrayIndexFastFail);
		case Verse::EOpcode::TypeCastFastFail:
			return sizeof(Verse::FOpTypeCastFastFail);
		case Verse::EOpcode::QueryFastFail:
			return sizeof(Verse::FOpQueryFastFail);
		case Verse::EOpcode::EndFastFailureContext:
			return sizeof(Verse::FOpEndFastFailureContext);
		case Verse::EOpcode::BeginFailureContext:
			return sizeof(Verse::FOpBeginFailureContext);
		case Verse::EOpcode::EndFailureContext:
			return sizeof(Verse::FOpEndFailureContext);
		case Verse::EOpcode::SelfTask:
			return sizeof(Verse::FOpSelfTask);
		case Verse::EOpcode::BeginTask:
			return sizeof(Verse::FOpBeginTask);
		case Verse::EOpcode::CallTask:
			return sizeof(Verse::FOpCallTask);
		case Verse::EOpcode::EndTask:
			return sizeof(Verse::FOpEndTask);
		case Verse::EOpcode::BeginAwait:
			return sizeof(Verse::FOpBeginAwait);
		case Verse::EOpcode::AwaitSuccess:
			return sizeof(Verse::FOpAwaitSuccess);
		case Verse::EOpcode::EndAwait:
			return sizeof(Verse::FOpEndAwait);
		case Verse::EOpcode::BeginBatch:
			return sizeof(Verse::FOpBeginBatch);
		case Verse::EOpcode::EndBatch:
			return sizeof(Verse::FOpEndBatch);
		case Verse::EOpcode::Yield:
			return sizeof(Verse::FOpYield);
		case Verse::EOpcode::NewSemaphore:
			return sizeof(Verse::FOpNewSemaphore);
		case Verse::EOpcode::WaitSemaphore:
			return sizeof(Verse::FOpWaitSemaphore);
		case Verse::EOpcode::Call:
			return sizeof(Verse::FOpCall);
		case Verse::EOpcode::CallWithSelf:
			return sizeof(Verse::FOpCallWithSelf);
		case Verse::EOpcode::Return:
			return sizeof(Verse::FOpReturn);
		case Verse::EOpcode::ReturnTrailed:
			return sizeof(Verse::FOpReturnTrailed);
		case Verse::EOpcode::ResumeUnwind:
			return sizeof(Verse::FOpResumeUnwind);
		case Verse::EOpcode::NewRef:
			return sizeof(Verse::FOpNewRef);
		case Verse::EOpcode::NewPersistentOrSessionWeakMapRef:
			return sizeof(Verse::FOpNewPersistentOrSessionWeakMapRef);
		case Verse::EOpcode::RefGet:
			return sizeof(Verse::FOpRefGet);
		case Verse::EOpcode::RefSet:
			return sizeof(Verse::FOpRefSet);
		case Verse::EOpcode::RefSetLive:
			return sizeof(Verse::FOpRefSetLive);
		case Verse::EOpcode::RefCallDomain:
			return sizeof(Verse::FOpRefCallDomain);
		case Verse::EOpcode::Freeze:
			return sizeof(Verse::FOpFreeze);
		case Verse::EOpcode::FreezeIfAccessor:
			return sizeof(Verse::FOpFreezeIfAccessor);
		case Verse::EOpcode::Melt:
			return sizeof(Verse::FOpMelt);
		case Verse::EOpcode::Length:
			return sizeof(Verse::FOpLength);
		case Verse::EOpcode::LengthWithEffects:
			return sizeof(Verse::FOpLengthWithEffects);
		case Verse::EOpcode::CallSet:
			return sizeof(Verse::FOpCallSet);
		case Verse::EOpcode::CallSetLive:
			return sizeof(Verse::FOpCallSetLive);
		case Verse::EOpcode::NewArray:
			return sizeof(Verse::FOpNewArray);
		case Verse::EOpcode::NewMutableArray:
			return sizeof(Verse::FOpNewMutableArray);
		case Verse::EOpcode::NewMutableArrayWithCapacity:
			return sizeof(Verse::FOpNewMutableArrayWithCapacity);
		case Verse::EOpcode::ArrayAdd:
			return sizeof(Verse::FOpArrayAdd);
		case Verse::EOpcode::InPlaceMakeImmutable:
			return sizeof(Verse::FOpInPlaceMakeImmutable);
		case Verse::EOpcode::NewOption:
			return sizeof(Verse::FOpNewOption);
		case Verse::EOpcode::NewUnionVariant:
			return sizeof(Verse::FOpNewUnionVariant);
		case Verse::EOpcode::GetUnionVariantPayload:
			return sizeof(Verse::FOpGetUnionVariantPayload);
		case Verse::EOpcode::GetUnionVariantTag:
			return sizeof(Verse::FOpGetUnionVariantTag);
		case Verse::EOpcode::NewMap:
			return sizeof(Verse::FOpNewMap);
		case Verse::EOpcode::MapKey:
			return sizeof(Verse::FOpMapKey);
		case Verse::EOpcode::MapValue:
			return sizeof(Verse::FOpMapValue);
		case Verse::EOpcode::NewClass:
			return sizeof(Verse::FOpNewClass);
		case Verse::EOpcode::BindNativeClass:
			return sizeof(Verse::FOpBindNativeClass);
		case Verse::EOpcode::ConstructNativeDefaultObject:
			return sizeof(Verse::FOpConstructNativeDefaultObject);
		case Verse::EOpcode::LoadImport:
			return sizeof(Verse::FOpLoadImport);
		case Verse::EOpcode::JumpIfDefaultSubObject:
			return sizeof(Verse::FOpJumpIfDefaultSubObject);
		case Verse::EOpcode::BeginModule:
			return sizeof(Verse::FOpBeginModule);
		case Verse::EOpcode::EndModule:
			return sizeof(Verse::FOpEndModule);
		case Verse::EOpcode::EndModuleData:
			return sizeof(Verse::FOpEndModuleData);
		case Verse::EOpcode::NewObject:
			return sizeof(Verse::FOpNewObject);
		case Verse::EOpcode::NewObjectICClass:
			return sizeof(Verse::FOpNewObjectICClass);
		case Verse::EOpcode::LoadField:
			return sizeof(Verse::FOpLoadField);
		case Verse::EOpcode::LoadFieldICOffset:
			return sizeof(Verse::FOpLoadFieldICOffset);
		case Verse::EOpcode::LoadFieldICConstant:
			return sizeof(Verse::FOpLoadFieldICConstant);
		case Verse::EOpcode::LoadFieldICFunction:
			return sizeof(Verse::FOpLoadFieldICFunction);
		case Verse::EOpcode::LoadFieldICNativeFunction:
			return sizeof(Verse::FOpLoadFieldICNativeFunction);
		case Verse::EOpcode::LoadFieldICAccessor:
			return sizeof(Verse::FOpLoadFieldICAccessor);
		case Verse::EOpcode::LoadFieldFromSuper:
			return sizeof(Verse::FOpLoadFieldFromSuper);
		case Verse::EOpcode::CreateField:
			return sizeof(Verse::FOpCreateField);
		case Verse::EOpcode::CreateFieldICValueObjectConstant:
			return sizeof(Verse::FOpCreateFieldICValueObjectConstant);
		case Verse::EOpcode::CreateFieldICValueObjectField:
			return sizeof(Verse::FOpCreateFieldICValueObjectField);
		case Verse::EOpcode::CreateFieldICNativeStruct:
			return sizeof(Verse::FOpCreateFieldICNativeStruct);
		case Verse::EOpcode::CreateFieldICUObject:
			return sizeof(Verse::FOpCreateFieldICUObject);
		case Verse::EOpcode::UnifyField:
			return sizeof(Verse::FOpUnifyField);
		case Verse::EOpcode::InitializeVar:
			return sizeof(Verse::FOpInitializeVar);
		case Verse::EOpcode::SetField:
			return sizeof(Verse::FOpSetField);
		case Verse::EOpcode::SetFieldLive:
			return sizeof(Verse::FOpSetFieldLive);
		case Verse::EOpcode::UnifyNativeObject:
			return sizeof(Verse::FOpUnifyNativeObject);
		case Verse::EOpcode::UnwrapNativeConstructorWrapper:
			return sizeof(Verse::FOpUnwrapNativeConstructorWrapper);
		case Verse::EOpcode::NewScope:
			return sizeof(Verse::FOpNewScope);
		case Verse::EOpcode::NewFunction:
			return sizeof(Verse::FOpNewFunction);
		case Verse::EOpcode::LoadParentScope:
			return sizeof(Verse::FOpLoadParentScope);
		case Verse::EOpcode::LoadCapture:
			return sizeof(Verse::FOpLoadCapture);
		case Verse::EOpcode::BeginProfileBlock:
			return sizeof(Verse::FOpBeginProfileBlock);
		case Verse::EOpcode::EndProfileBlock:
			return sizeof(Verse::FOpEndProfileBlock);
		case Verse::EOpcode::LoadConstructor:
			return sizeof(Verse::FOpLoadConstructor);
		case Verse::EOpcode::Neq:
			return sizeof(Verse::FOpNeq);
		case Verse::EOpcode::Lt:
			return sizeof(Verse::FOpLt);
		case Verse::EOpcode::Lte:
			return sizeof(Verse::FOpLte);
		case Verse::EOpcode::Gt:
			return sizeof(Verse::FOpGt);
		case Verse::EOpcode::Gte:
			return sizeof(Verse::FOpGte);
		default:
			return 0;
	}
}

template <typename TEncoder>
AUTORTFM_DISABLE void EncodeOp(TEncoder& E, Verse::FOp& Op)
{
	switch (Op.Opcode)
	{
		case Verse::EOpcode::Add:
		{
			Verse::FOpAdd& O = static_cast<Verse::FOpAdd&>(Op);
			E.Opcode(0);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::Sub:
		{
			Verse::FOpSub& O = static_cast<Verse::FOpSub&>(Op);
			E.Opcode(1);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::Mul:
		{
			Verse::FOpMul& O = static_cast<Verse::FOpMul&>(Op);
			E.Opcode(2);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::Div:
		{
			Verse::FOpDiv& O = static_cast<Verse::FOpDiv&>(Op);
			E.Opcode(3);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::Mod:
		{
			Verse::FOpMod& O = static_cast<Verse::FOpMod&>(Op);
			E.Opcode(4);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::CanFastAppendToArrayFastFail:
		{
			Verse::FOpCanFastAppendToArrayFastFail& O = static_cast<Verse::FOpCanFastAppendToArrayFastFail&>(Op);
			E.Opcode(5);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Ref, ERole::Use);
			E.Value(O.MaybeMutableArray, ERole::Use);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::FastAppendToArray:
		{
			Verse::FOpFastAppendToArray& O = static_cast<Verse::FOpFastAppendToArray&>(Op);
			E.Opcode(6);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::MutableAdd:
		{
			Verse::FOpMutableAdd& O = static_cast<Verse::FOpMutableAdd&>(Op);
			E.Opcode(7);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::Neg:
		{
			Verse::FOpNeg& O = static_cast<Verse::FOpNeg&>(Op);
			E.Opcode(8);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Source, ERole::Use);
			return;
		}
		case Verse::EOpcode::Query:
		{
			Verse::FOpQuery& O = static_cast<Verse::FOpQuery&>(Op);
			E.Opcode(9);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Source, ERole::Use);
			return;
		}
		case Verse::EOpcode::Err:
		{
			E.Opcode(10);
			return;
		}
		case Verse::EOpcode::Tracepoint:
		{
			Verse::FOpTracepoint& O = static_cast<Verse::FOpTracepoint&>(Op);
			E.Opcode(11);
			E.Cell(O.Name, ERole::Immediate);
			return;
		}
		case Verse::EOpcode::Move:
		{
			Verse::FOpMove& O = static_cast<Verse::FOpMove&>(Op);
			E.Opcode(12);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Source, ERole::Use);
			return;
		}
		case Verse::EOpcode::MoveTrailed:
		{
			Verse::FOpMoveTrailed& O = static_cast<Verse::FOpMoveTrailed&>(Op);
			E.Opcode(13);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Source, ERole::Use);
			return;
		}
		case Verse::EOpcode::MoveNonComparable:
		{
			Verse::FOpMoveNonComparable& O = static_cast<Verse::FOpMoveNonComparable&>(Op);
			E.Opcode(14);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Source, ERole::Use);
			return;
		}
		case Verse::EOpcode::Reset:
		{
			Verse::FOpReset& O = static_cast<Verse::FOpReset&>(Op);
			E.Opcode(15);
			E.Register(O.Dest, ERole::ClobberDef);
			E.LiveRange(O.LiveRange, ERole::Const);
			return;
		}
		case Verse::EOpcode::ResetNonTrailed:
		{
			Verse::FOpResetNonTrailed& O = static_cast<Verse::FOpResetNonTrailed&>(Op);
			E.Opcode(16);
			E.Register(O.Dest, ERole::ClobberDef);
			E.LiveRange(O.LiveRange, ERole::Const);
			return;
		}
		case Verse::EOpcode::Jump:
		{
			Verse::FOpJump& O = static_cast<Verse::FOpJump&>(Op);
			E.Opcode(17);
			E.Label(O.JumpOffset, ERole::Jump);
			return;
		}
		case Verse::EOpcode::JumpIfInitialized:
		{
			Verse::FOpJumpIfInitialized& O = static_cast<Verse::FOpJumpIfInitialized&>(Op);
			E.Opcode(18);
			E.Value(O.Source, ERole::Use);
			E.Label(O.JumpOffset, ERole::Jump);
			return;
		}
		case Verse::EOpcode::Switch:
		{
			Verse::FOpSwitch& O = static_cast<Verse::FOpSwitch&>(Op);
			E.Opcode(19);
			E.Value(O.Which, ERole::Use);
			E.LabelRange(O.JumpOffsets, ERole::Jump);
			return;
		}
		case Verse::EOpcode::LtFastFail:
		{
			Verse::FOpLtFastFail& O = static_cast<Verse::FOpLtFastFail&>(Op);
			E.Opcode(20);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Lhs, ERole::Use);
			E.Value(O.Rhs, ERole::Use);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::LteFastFail:
		{
			Verse::FOpLteFastFail& O = static_cast<Verse::FOpLteFastFail&>(Op);
			E.Opcode(21);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Lhs, ERole::Use);
			E.Value(O.Rhs, ERole::Use);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::GtFastFail:
		{
			Verse::FOpGtFastFail& O = static_cast<Verse::FOpGtFastFail&>(Op);
			E.Opcode(22);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Lhs, ERole::Use);
			E.Value(O.Rhs, ERole::Use);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::GteFastFail:
		{
			Verse::FOpGteFastFail& O = static_cast<Verse::FOpGteFastFail&>(Op);
			E.Opcode(23);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Lhs, ERole::Use);
			E.Value(O.Rhs, ERole::Use);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::EqFastFail:
		{
			Verse::FOpEqFastFail& O = static_cast<Verse::FOpEqFastFail&>(Op);
			E.Opcode(24);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Lhs, ERole::Use);
			E.Value(O.Rhs, ERole::Use);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::NeqFastFail:
		{
			Verse::FOpNeqFastFail& O = static_cast<Verse::FOpNeqFastFail&>(Op);
			E.Opcode(25);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Lhs, ERole::Use);
			E.Value(O.Rhs, ERole::Use);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::ArrayIndexFastFail:
		{
			Verse::FOpArrayIndexFastFail& O = static_cast<Verse::FOpArrayIndexFastFail&>(Op);
			E.Opcode(26);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Array, ERole::Use);
			E.Value(O.Index, ERole::Use);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::TypeCastFastFail:
		{
			Verse::FOpTypeCastFastFail& O = static_cast<Verse::FOpTypeCastFastFail&>(Op);
			E.Opcode(27);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Type, ERole::Use);
			E.Value(O.Value, ERole::Use);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::QueryFastFail:
		{
			Verse::FOpQueryFastFail& O = static_cast<Verse::FOpQueryFastFail&>(Op);
			E.Opcode(28);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Source, ERole::Use);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::EndFastFailureContext:
		{
			Verse::FOpEndFastFailureContext& O = static_cast<Verse::FOpEndFastFailureContext&>(Op);
			E.Opcode(29);
			E.Register(O.OuterLeniencyIndicator, ERole::UnifyDef);
			E.Value(O.LeniencyIndicator, ERole::Use);
			E.Label(O.OnDone, ERole::Jump);
			return;
		}
		case Verse::EOpcode::BeginFailureContext:
		{
			Verse::FOpBeginFailureContext& O = static_cast<Verse::FOpBeginFailureContext&>(Op);
			E.Opcode(30);
			E.Label(O.OnFailure, ERole::Jump);
			E.FailureContextId(O.Id, ERole::Const);
			return;
		}
		case Verse::EOpcode::EndFailureContext:
		{
			Verse::FOpEndFailureContext& O = static_cast<Verse::FOpEndFailureContext&>(Op);
			E.Opcode(31);
			E.Label(O.Done, ERole::Jump);
			E.FailureContextId(O.Id, ERole::Const);
			return;
		}
		case Verse::EOpcode::SelfTask:
		{
			Verse::FOpSelfTask& O = static_cast<Verse::FOpSelfTask&>(Op);
			E.Opcode(32);
			E.Register(O.Dest, ERole::UnifyDef);
			return;
		}
		case Verse::EOpcode::BeginTask:
		{
			Verse::FOpBeginTask& O = static_cast<Verse::FOpBeginTask&>(Op);
			E.Opcode(33);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Parent, ERole::Use);
			E.Bool(O.bAddToTaskGroup, ERole::Const);
			E.Label(O.OnYield, ERole::Jump);
			return;
		}
		case Verse::EOpcode::CallTask:
		{
			Verse::FOpCallTask& O = static_cast<Verse::FOpCallTask&>(Op);
			E.Opcode(34);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Parent, ERole::Use);
			E.Value(O.Callee, ERole::Use);
			E.ValueRange(O.Arguments, ERole::Use);
			return;
		}
		case Verse::EOpcode::EndTask:
		{
			Verse::FOpEndTask& O = static_cast<Verse::FOpEndTask&>(Op);
			E.Opcode(35);
			E.OptRegister(O.Write, ERole::ClobberDef);
			E.OptRegister(O.Switch, ERole::ClobberDef);
			E.Value(O.Value, ERole::Use);
			E.Value(O.Which, ERole::Use);
			E.OptValue(O.Signal, ERole::Use);
			return;
		}
		case Verse::EOpcode::BeginAwait:
		{
			E.Opcode(36);
			return;
		}
		case Verse::EOpcode::AwaitSuccess:
		{
			E.Opcode(37);
			return;
		}
		case Verse::EOpcode::EndAwait:
		{
			E.Opcode(38);
			return;
		}
		case Verse::EOpcode::BeginBatch:
		{
			E.Opcode(39);
			return;
		}
		case Verse::EOpcode::EndBatch:
		{
			E.Opcode(40);
			return;
		}
		case Verse::EOpcode::Yield:
		{
			Verse::FOpYield& O = static_cast<Verse::FOpYield&>(Op);
			E.Opcode(41);
			E.Label(O.ResumeOffset, ERole::Jump);
			return;
		}
		case Verse::EOpcode::NewSemaphore:
		{
			Verse::FOpNewSemaphore& O = static_cast<Verse::FOpNewSemaphore&>(Op);
			E.Opcode(42);
			E.Register(O.Dest, ERole::UnifyDef);
			return;
		}
		case Verse::EOpcode::WaitSemaphore:
		{
			Verse::FOpWaitSemaphore& O = static_cast<Verse::FOpWaitSemaphore&>(Op);
			E.Opcode(43);
			E.Value(O.Source, ERole::Use);
			E.I32(O.Count, ERole::Const);
			return;
		}
		case Verse::EOpcode::Call:
		{
			Verse::FOpCall& O = static_cast<Verse::FOpCall&>(Op);
			E.Opcode(44);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Callee, ERole::Use);
			E.ValueRange(O.Arguments, ERole::Use);
			E.CellRange(O.NamedArguments, ERole::Immediate);
			E.ValueRange(O.NamedArgumentValues, ERole::Use);
			E.Bool(O.bCalleeYields, ERole::Const);
			return;
		}
		case Verse::EOpcode::CallWithSelf:
		{
			Verse::FOpCallWithSelf& O = static_cast<Verse::FOpCallWithSelf&>(Op);
			E.Opcode(45);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Callee, ERole::Use);
			E.Value(O.Self, ERole::Use);
			E.ValueRange(O.Arguments, ERole::Use);
			E.CellRange(O.NamedArguments, ERole::Immediate);
			E.ValueRange(O.NamedArgumentValues, ERole::Use);
			E.Bool(O.bCalleeYields, ERole::Const);
			return;
		}
		case Verse::EOpcode::Return:
		{
			Verse::FOpReturn& O = static_cast<Verse::FOpReturn&>(Op);
			E.Opcode(46);
			E.Value(O.Value, ERole::Use);
			return;
		}
		case Verse::EOpcode::ReturnTrailed:
		{
			Verse::FOpReturnTrailed& O = static_cast<Verse::FOpReturnTrailed&>(Op);
			E.Opcode(47);
			E.Value(O.Value, ERole::Use);
			return;
		}
		case Verse::EOpcode::ResumeUnwind:
		{
			E.Opcode(48);
			return;
		}
		case Verse::EOpcode::NewRef:
		{
			Verse::FOpNewRef& O = static_cast<Verse::FOpNewRef&>(Op);
			E.Opcode(49);
			E.Register(O.Dest, ERole::UnifyDef);
			E.OptValue(O.Domain, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewPersistentOrSessionWeakMapRef:
		{
			Verse::FOpNewPersistentOrSessionWeakMapRef& O = static_cast<Verse::FOpNewPersistentOrSessionWeakMapRef&>(Op);
			E.Opcode(50);
			E.Register(O.Dest, ERole::UnifyDef);
			return;
		}
		case Verse::EOpcode::RefGet:
		{
			Verse::FOpRefGet& O = static_cast<Verse::FOpRefGet&>(Op);
			E.Opcode(51);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Ref, ERole::Use);
			return;
		}
		case Verse::EOpcode::RefSet:
		{
			Verse::FOpRefSet& O = static_cast<Verse::FOpRefSet&>(Op);
			E.Opcode(52);
			E.Value(O.Ref, ERole::Use);
			E.Value(O.Value, ERole::Use);
			return;
		}
		case Verse::EOpcode::RefSetLive:
		{
			Verse::FOpRefSetLive& O = static_cast<Verse::FOpRefSetLive&>(Op);
			E.Opcode(53);
			E.Value(O.Ref, ERole::Use);
			E.Value(O.Value, ERole::Use);
			E.Value(O.Task, ERole::Use);
			return;
		}
		case Verse::EOpcode::RefCallDomain:
		{
			Verse::FOpRefCallDomain& O = static_cast<Verse::FOpRefCallDomain&>(Op);
			E.Opcode(54);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Ref, ERole::Use);
			E.Value(O.Argument, ERole::Use);
			return;
		}
		case Verse::EOpcode::Freeze:
		{
			Verse::FOpFreeze& O = static_cast<Verse::FOpFreeze&>(Op);
			E.Opcode(55);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Value, ERole::Use);
			return;
		}
		case Verse::EOpcode::FreezeIfAccessor:
		{
			Verse::FOpFreezeIfAccessor& O = static_cast<Verse::FOpFreezeIfAccessor&>(Op);
			E.Opcode(56);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Value, ERole::Use);
			return;
		}
		case Verse::EOpcode::Melt:
		{
			Verse::FOpMelt& O = static_cast<Verse::FOpMelt&>(Op);
			E.Opcode(57);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Value, ERole::Use);
			return;
		}
		case Verse::EOpcode::Length:
		{
			Verse::FOpLength& O = static_cast<Verse::FOpLength&>(Op);
			E.Opcode(58);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Container, ERole::Use);
			return;
		}
		case Verse::EOpcode::LengthWithEffects:
		{
			Verse::FOpLengthWithEffects& O = static_cast<Verse::FOpLengthWithEffects&>(Op);
			E.Opcode(59);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Container, ERole::Use);
			return;
		}
		case Verse::EOpcode::CallSet:
		{
			Verse::FOpCallSet& O = static_cast<Verse::FOpCallSet&>(Op);
			E.Opcode(60);
			E.Value(O.Container, ERole::Use);
			E.Value(O.Index, ERole::Use);
			E.Value(O.ValueToSet, ERole::Use);
			return;
		}
		case Verse::EOpcode::CallSetLive:
		{
			Verse::FOpCallSetLive& O = static_cast<Verse::FOpCallSetLive&>(Op);
			E.Opcode(61);
			E.Value(O.Container, ERole::Use);
			E.Value(O.Index, ERole::Use);
			E.Value(O.ValueToSet, ERole::Use);
			E.Value(O.Task, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewArray:
		{
			Verse::FOpNewArray& O = static_cast<Verse::FOpNewArray&>(Op);
			E.Opcode(62);
			E.Register(O.Dest, ERole::UnifyDef);
			E.ValueRange(O.Values, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewMutableArray:
		{
			Verse::FOpNewMutableArray& O = static_cast<Verse::FOpNewMutableArray&>(Op);
			E.Opcode(63);
			E.Register(O.Dest, ERole::UnifyDef);
			E.ValueRange(O.Values, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewMutableArrayWithCapacity:
		{
			Verse::FOpNewMutableArrayWithCapacity& O = static_cast<Verse::FOpNewMutableArrayWithCapacity&>(Op);
			E.Opcode(64);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Size, ERole::Use);
			return;
		}
		case Verse::EOpcode::ArrayAdd:
		{
			Verse::FOpArrayAdd& O = static_cast<Verse::FOpArrayAdd&>(Op);
			E.Opcode(65);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Container, ERole::Use);
			E.Value(O.ValueToAdd, ERole::Use);
			E.Bool(O.bTransactional, ERole::Const);
			return;
		}
		case Verse::EOpcode::InPlaceMakeImmutable:
		{
			Verse::FOpInPlaceMakeImmutable& O = static_cast<Verse::FOpInPlaceMakeImmutable&>(Op);
			E.Opcode(66);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Container, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewOption:
		{
			Verse::FOpNewOption& O = static_cast<Verse::FOpNewOption&>(Op);
			E.Opcode(67);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Value, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewUnionVariant:
		{
			Verse::FOpNewUnionVariant& O = static_cast<Verse::FOpNewUnionVariant&>(Op);
			E.Opcode(68);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Tag, ERole::Use);
			E.Value(O.Payload, ERole::Use);
			return;
		}
		case Verse::EOpcode::GetUnionVariantPayload:
		{
			Verse::FOpGetUnionVariantPayload& O = static_cast<Verse::FOpGetUnionVariantPayload&>(Op);
			E.Opcode(69);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Source, ERole::Use);
			return;
		}
		case Verse::EOpcode::GetUnionVariantTag:
		{
			Verse::FOpGetUnionVariantTag& O = static_cast<Verse::FOpGetUnionVariantTag&>(Op);
			E.Opcode(70);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Source, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewMap:
		{
			Verse::FOpNewMap& O = static_cast<Verse::FOpNewMap&>(Op);
			E.Opcode(71);
			E.Register(O.Dest, ERole::UnifyDef);
			E.ValueRange(O.Keys, ERole::Use);
			E.ValueRange(O.Values, ERole::Use);
			return;
		}
		case Verse::EOpcode::MapKey:
		{
			Verse::FOpMapKey& O = static_cast<Verse::FOpMapKey&>(Op);
			E.Opcode(72);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Map, ERole::Use);
			E.Value(O.Index, ERole::Use);
			return;
		}
		case Verse::EOpcode::MapValue:
		{
			Verse::FOpMapValue& O = static_cast<Verse::FOpMapValue&>(Op);
			E.Opcode(73);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Map, ERole::Use);
			E.Value(O.Index, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewClass:
		{
			Verse::FOpNewClass& O = static_cast<Verse::FOpNewClass&>(Op);
			E.Opcode(74);
			E.Register(O.ClassDest, ERole::UnifyDef);
			E.Register(O.ArchetypeDest, ERole::UnifyDef);
			E.Register(O.ConstructorDest, ERole::UnifyDef);
			E.Register(O.BlocksDest, ERole::UnifyDef);
			E.Cell(O.Package, ERole::Immediate);
			E.Cell(O.RelativePath, ERole::Immediate);
			E.Cell(O.ClassName, ERole::Immediate);
			E.ValueImmRange(O.AttributeIndices, ERole::Immediate);
			E.ValueRange(O.Attributes, ERole::Use);
			E.OptValueImm(O.ImportStruct, ERole::Immediate);
			E.ValueRange(O.Inherited, ERole::Use);
			E.Cell(O.Archetype, ERole::Immediate);
			E.OptCell(O.ConstructorBody, ERole::Immediate);
			E.OptCell(O.Blocks, ERole::Immediate);
			E.Bool(O.bNativeBound, ERole::Const);
			E.ClassKind(O.ClassKind, ERole::Const);
			E.ClassFlags(O.Flags, ERole::Const);
			return;
		}
		case Verse::EOpcode::BindNativeClass:
		{
			Verse::FOpBindNativeClass& O = static_cast<Verse::FOpBindNativeClass&>(Op);
			E.Opcode(75);
			E.Value(O.Class, ERole::Use);
			E.Bool(O.bImported, ERole::Const);
			return;
		}
		case Verse::EOpcode::ConstructNativeDefaultObject:
		{
			Verse::FOpConstructNativeDefaultObject& O = static_cast<Verse::FOpConstructNativeDefaultObject&>(Op);
			E.Opcode(76);
			E.Value(O.Class, ERole::Use);
			return;
		}
		case Verse::EOpcode::LoadImport:
		{
			Verse::FOpLoadImport& O = static_cast<Verse::FOpLoadImport&>(Op);
			E.Opcode(77);
			E.Value(O.Class, ERole::Use);
			E.AssetPath(O.ImportPath, ERole::Const);
			return;
		}
		case Verse::EOpcode::JumpIfDefaultSubObject:
		{
			Verse::FOpJumpIfDefaultSubObject& O = static_cast<Verse::FOpJumpIfDefaultSubObject&>(Op);
			E.Opcode(78);
			E.Value(O.Object, ERole::Use);
			E.Label(O.OnDefaultSubObject, ERole::Jump);
			return;
		}
		case Verse::EOpcode::BeginModule:
		{
			Verse::FOpBeginModule& O = static_cast<Verse::FOpBeginModule&>(Op);
			E.Opcode(79);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Package, ERole::Use);
			E.Cell(O.ModuleName, ERole::Immediate);
			return;
		}
		case Verse::EOpcode::EndModule:
		{
			Verse::FOpEndModule& O = static_cast<Verse::FOpEndModule&>(Op);
			E.Opcode(80);
			E.Value(O.Module, ERole::Use);
			return;
		}
		case Verse::EOpcode::EndModuleData:
		{
			Verse::FOpEndModuleData& O = static_cast<Verse::FOpEndModuleData&>(Op);
			E.Opcode(81);
			E.Cell(O.FieldName, ERole::Immediate);
			E.Value(O.Value, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewObject:
		{
			Verse::FOpNewObject& O = static_cast<Verse::FOpNewObject&>(Op);
			E.Opcode(82);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Archetype, ERole::Use);
			E.Value(O.Class, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewObjectICClass:
		{
			Verse::FOpNewObjectICClass& O = static_cast<Verse::FOpNewObjectICClass&>(Op);
			E.Opcode(82); // written as NewObject
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Archetype, ERole::Use);
			E.Value(O.Class, ERole::Use);
			return;
		}
		case Verse::EOpcode::LoadField:
		{
			Verse::FOpLoadField& O = static_cast<Verse::FOpLoadField&>(Op);
			E.Opcode(84);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			return;
		}
		case Verse::EOpcode::LoadFieldICOffset:
		{
			Verse::FOpLoadFieldICOffset& O = static_cast<Verse::FOpLoadFieldICOffset&>(Op);
			E.Opcode(84); // written as LoadField
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			return;
		}
		case Verse::EOpcode::LoadFieldICConstant:
		{
			Verse::FOpLoadFieldICConstant& O = static_cast<Verse::FOpLoadFieldICConstant&>(Op);
			E.Opcode(84); // written as LoadField
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			return;
		}
		case Verse::EOpcode::LoadFieldICFunction:
		{
			Verse::FOpLoadFieldICFunction& O = static_cast<Verse::FOpLoadFieldICFunction&>(Op);
			E.Opcode(84); // written as LoadField
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			return;
		}
		case Verse::EOpcode::LoadFieldICNativeFunction:
		{
			Verse::FOpLoadFieldICNativeFunction& O = static_cast<Verse::FOpLoadFieldICNativeFunction&>(Op);
			E.Opcode(84); // written as LoadField
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			return;
		}
		case Verse::EOpcode::LoadFieldICAccessor:
		{
			Verse::FOpLoadFieldICAccessor& O = static_cast<Verse::FOpLoadFieldICAccessor&>(Op);
			E.Opcode(84); // written as LoadField
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			return;
		}
		case Verse::EOpcode::LoadFieldFromSuper:
		{
			Verse::FOpLoadFieldFromSuper& O = static_cast<Verse::FOpLoadFieldFromSuper&>(Op);
			E.Opcode(90);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Scope, ERole::Use);
			E.Value(O.Self, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			return;
		}
		case Verse::EOpcode::CreateField:
		{
			Verse::FOpCreateField& O = static_cast<Verse::FOpCreateField&>(Op);
			E.Opcode(91);
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Token, ERole::Use);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::CreateFieldICValueObjectConstant:
		{
			Verse::FOpCreateFieldICValueObjectConstant& O = static_cast<Verse::FOpCreateFieldICValueObjectConstant&>(Op);
			E.Opcode(91); // written as CreateField
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Token, ERole::Use);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::CreateFieldICValueObjectField:
		{
			Verse::FOpCreateFieldICValueObjectField& O = static_cast<Verse::FOpCreateFieldICValueObjectField&>(Op);
			E.Opcode(91); // written as CreateField
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Token, ERole::Use);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::CreateFieldICNativeStruct:
		{
			Verse::FOpCreateFieldICNativeStruct& O = static_cast<Verse::FOpCreateFieldICNativeStruct&>(Op);
			E.Opcode(91); // written as CreateField
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Token, ERole::Use);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::CreateFieldICUObject:
		{
			Verse::FOpCreateFieldICUObject& O = static_cast<Verse::FOpCreateFieldICUObject&>(Op);
			E.Opcode(91); // written as CreateField
			E.Register(O.LeniencyIndicator, ERole::UnifyDef);
			E.Value(O.Token, ERole::Use);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			E.Label(O.OnFailure, ERole::Jump);
			return;
		}
		case Verse::EOpcode::UnifyField:
		{
			Verse::FOpUnifyField& O = static_cast<Verse::FOpUnifyField&>(Op);
			E.Opcode(96);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			E.Value(O.Value, ERole::Use);
			return;
		}
		case Verse::EOpcode::InitializeVar:
		{
			Verse::FOpInitializeVar& O = static_cast<Verse::FOpInitializeVar&>(Op);
			E.Opcode(97);
			E.Register(O.TokenDest, ERole::UnifyDef);
			E.Value(O.Token, ERole::Use);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			E.Value(O.Value, ERole::Use);
			E.OptValue(O.ValueDomain, ERole::Use);
			E.Bool(O.bCheckIfVariableAllocationIsAllowed, ERole::Const);
			return;
		}
		case Verse::EOpcode::SetField:
		{
			Verse::FOpSetField& O = static_cast<Verse::FOpSetField&>(Op);
			E.Opcode(98);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			E.Value(O.Value, ERole::Use);
			return;
		}
		case Verse::EOpcode::SetFieldLive:
		{
			Verse::FOpSetFieldLive& O = static_cast<Verse::FOpSetFieldLive&>(Op);
			E.Opcode(99);
			E.Value(O.Object, ERole::Use);
			E.Cell(O.Name, ERole::Immediate);
			E.Value(O.Value, ERole::Use);
			E.Value(O.Task, ERole::Use);
			return;
		}
		case Verse::EOpcode::UnifyNativeObject:
		{
			Verse::FOpUnifyNativeObject& O = static_cast<Verse::FOpUnifyNativeObject&>(Op);
			E.Opcode(100);
			E.Value(O.Token, ERole::Use);
			E.Value(O.Object, ERole::Use);
			return;
		}
		case Verse::EOpcode::UnwrapNativeConstructorWrapper:
		{
			Verse::FOpUnwrapNativeConstructorWrapper& O = static_cast<Verse::FOpUnwrapNativeConstructorWrapper&>(Op);
			E.Opcode(101);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Object, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewScope:
		{
			Verse::FOpNewScope& O = static_cast<Verse::FOpNewScope&>(Op);
			E.Opcode(102);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.ParentScope, ERole::Use);
			E.ValueRange(O.Captures, ERole::Use);
			return;
		}
		case Verse::EOpcode::NewFunction:
		{
			Verse::FOpNewFunction& O = static_cast<Verse::FOpNewFunction&>(Op);
			E.Opcode(103);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Procedure, ERole::Use);
			E.Value(O.Self, ERole::Use);
			E.Value(O.ParentScope, ERole::Use);
			return;
		}
		case Verse::EOpcode::LoadParentScope:
		{
			Verse::FOpLoadParentScope& O = static_cast<Verse::FOpLoadParentScope&>(Op);
			E.Opcode(104);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Scope, ERole::Use);
			return;
		}
		case Verse::EOpcode::LoadCapture:
		{
			Verse::FOpLoadCapture& O = static_cast<Verse::FOpLoadCapture&>(Op);
			E.Opcode(105);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Scope, ERole::Use);
			E.U32(O.Index, ERole::Const);
			return;
		}
		case Verse::EOpcode::BeginProfileBlock:
		{
			Verse::FOpBeginProfileBlock& O = static_cast<Verse::FOpBeginProfileBlock&>(Op);
			E.Opcode(106);
			E.Register(O.Dest, ERole::UnifyDef);
			return;
		}
		case Verse::EOpcode::EndProfileBlock:
		{
			Verse::FOpEndProfileBlock& O = static_cast<Verse::FOpEndProfileBlock&>(Op);
			E.Opcode(107);
			E.Value(O.WallTimeStart, ERole::Use);
			E.Value(O.UserTag, ERole::Use);
			E.Cell(O.SnippetPath, ERole::Immediate);
			E.Value(O.BeginRow, ERole::Use);
			E.Value(O.BeginColumn, ERole::Use);
			E.Value(O.EndRow, ERole::Use);
			E.Value(O.EndColumn, ERole::Use);
			return;
		}
		case Verse::EOpcode::LoadConstructor:
		{
			Verse::FOpLoadConstructor& O = static_cast<Verse::FOpLoadConstructor&>(Op);
			E.Opcode(108);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.Class, ERole::Use);
			return;
		}
		case Verse::EOpcode::Neq:
		{
			Verse::FOpNeq& O = static_cast<Verse::FOpNeq&>(Op);
			E.Opcode(109);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::Lt:
		{
			Verse::FOpLt& O = static_cast<Verse::FOpLt&>(Op);
			E.Opcode(110);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::Lte:
		{
			Verse::FOpLte& O = static_cast<Verse::FOpLte&>(Op);
			E.Opcode(111);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::Gt:
		{
			Verse::FOpGt& O = static_cast<Verse::FOpGt&>(Op);
			E.Opcode(112);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		case Verse::EOpcode::Gte:
		{
			Verse::FOpGte& O = static_cast<Verse::FOpGte&>(Op);
			E.Opcode(113);
			E.Register(O.Dest, ERole::UnifyDef);
			E.Value(O.LeftSource, ERole::Use);
			E.Value(O.RightSource, ERole::Use);
			return;
		}
		default:
			break;
	}
	E.UnknownOpcode(Op);
}

} // namespace GodotVerse::Vbc
