// Generated by tools/gen_vbc_ops.py --emit-cpp from docs/web-vm/ops.json.
// Do not hand-edit -- regenerate instead. See docs/web-vm/format.md §5.1.
#pragma once

#include <cstdint>

namespace vbc {

enum class VbcOperandRole : uint8_t {
	Use,
	Immediate,
	UnifyDef,
	ClobberDef,
	Const,
	Jump,
};

enum class VbcOperandKind : uint8_t {
	Register,
	Value,
	ValueImm,
	CellVUniqueString,
	CellVPackage,
	CellVArray,
	CellVArchetype,
	CellVProcedure,
	Label,
	Bool,
	I32,
	U32,
	U64,
	LiveRange,
	FailureContextId,
	AssetPath,
	ClassRefIc,
	EnumClassKind,
	EnumClassFlags,
};

struct VbcOperandDesc {
	const char *name;
	VbcOperandRole role;
	VbcOperandKind kind;
	bool variadic;
	bool optional;
	bool cache;
};

enum class VbcOp : uint16_t {
	Add = 0,
	Sub = 1,
	Mul = 2,
	Div = 3,
	Mod = 4,
	CanFastAppendToArrayFastFail = 5,
	FastAppendToArray = 6,
	MutableAdd = 7,
	Neg = 8,
	Query = 9,
	Err = 10,
	Tracepoint = 11,
	Move = 12,
	MoveTrailed = 13,
	MoveNonComparable = 14,
	Reset = 15,
	ResetNonTrailed = 16,
	Jump = 17,
	JumpIfInitialized = 18,
	Switch = 19,
	LtFastFail = 20,
	LteFastFail = 21,
	GtFastFail = 22,
	GteFastFail = 23,
	EqFastFail = 24,
	NeqFastFail = 25,
	ArrayIndexFastFail = 26,
	TypeCastFastFail = 27,
	QueryFastFail = 28,
	EndFastFailureContext = 29,
	BeginFailureContext = 30,
	EndFailureContext = 31,
	SelfTask = 32,
	BeginTask = 33,
	CallTask = 34,
	EndTask = 35,
	BeginAwait = 36,
	AwaitSuccess = 37,
	EndAwait = 38,
	BeginBatch = 39,
	EndBatch = 40,
	Yield = 41,
	NewSemaphore = 42,
	WaitSemaphore = 43,
	Call = 44,
	CallWithSelf = 45,
	Return = 46,
	ReturnTrailed = 47,
	ResumeUnwind = 48,
	NewRef = 49,
	NewPersistentOrSessionWeakMapRef = 50,
	RefGet = 51,
	RefSet = 52,
	RefSetLive = 53,
	RefCallDomain = 54,
	Freeze = 55,
	FreezeIfAccessor = 56,
	Melt = 57,
	Length = 58,
	LengthWithEffects = 59,
	CallSet = 60,
	CallSetLive = 61,
	NewArray = 62,
	NewMutableArray = 63,
	NewMutableArrayWithCapacity = 64,
	ArrayAdd = 65,
	InPlaceMakeImmutable = 66,
	NewOption = 67,
	NewUnionVariant = 68,
	GetUnionVariantPayload = 69,
	GetUnionVariantTag = 70,
	NewMap = 71,
	MapKey = 72,
	MapValue = 73,
	NewClass = 74,
	BindNativeClass = 75,
	ConstructNativeDefaultObject = 76,
	LoadImport = 77,
	JumpIfDefaultSubObject = 78,
	BeginModule = 79,
	EndModule = 80,
	EndModuleData = 81,
	NewObject = 82,
	NewObjectICClass = 83,
	LoadField = 84,
	LoadFieldICOffset = 85,
	LoadFieldICConstant = 86,
	LoadFieldICFunction = 87,
	LoadFieldICNativeFunction = 88,
	LoadFieldICAccessor = 89,
	LoadFieldFromSuper = 90,
	CreateField = 91,
	CreateFieldICValueObjectConstant = 92,
	CreateFieldICValueObjectField = 93,
	CreateFieldICNativeStruct = 94,
	CreateFieldICUObject = 95,
	UnifyField = 96,
	InitializeVar = 97,
	SetField = 98,
	SetFieldLive = 99,
	UnifyNativeObject = 100,
	UnwrapNativeConstructorWrapper = 101,
	NewScope = 102,
	NewFunction = 103,
	LoadParentScope = 104,
	LoadCapture = 105,
	BeginProfileBlock = 106,
	EndProfileBlock = 107,
	LoadConstructor = 108,
	Neq = 109,
	Lt = 110,
	Lte = 111,
	Gt = 112,
	Gte = 113,
};

constexpr int32_t kVbcOpCount = 114;

constexpr VbcOperandDesc kVbcOperands_Add[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Sub[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Mul[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Div[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Mod[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_CanFastAppendToArrayFastFail[] = {
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Ref", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"MaybeMutableArray", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_FastAppendToArray[] = {
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_MutableAdd[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Neg[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Source", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Query[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Source", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Tracepoint[] = {
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Move[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Source", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_MoveTrailed[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Source", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_MoveNonComparable[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Source", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Reset[] = {
	{"Dest", VbcOperandRole::ClobberDef, VbcOperandKind::Register, false, false, false},
	{"LiveRange", VbcOperandRole::Const, VbcOperandKind::LiveRange, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_ResetNonTrailed[] = {
	{"Dest", VbcOperandRole::ClobberDef, VbcOperandKind::Register, false, false, false},
	{"LiveRange", VbcOperandRole::Const, VbcOperandKind::LiveRange, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Jump[] = {
	{"JumpOffset", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_JumpIfInitialized[] = {
	{"Source", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"JumpOffset", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Switch[] = {
	{"Which", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"JumpOffsets", VbcOperandRole::Jump, VbcOperandKind::Label, true, false, false},
};

constexpr VbcOperandDesc kVbcOperands_LtFastFail[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Lhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Rhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_LteFastFail[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Lhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Rhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_GtFastFail[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Lhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Rhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_GteFastFail[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Lhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Rhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_EqFastFail[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Lhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Rhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NeqFastFail[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Lhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Rhs", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_ArrayIndexFastFail[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Array", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Index", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_TypeCastFastFail[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Type", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_QueryFastFail[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Source", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_EndFastFailureContext[] = {
	{"OuterLeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeniencyIndicator", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnDone", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_BeginFailureContext[] = {
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
	{"Id", VbcOperandRole::Const, VbcOperandKind::FailureContextId, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_EndFailureContext[] = {
	{"Done", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
	{"Id", VbcOperandRole::Const, VbcOperandKind::FailureContextId, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_SelfTask[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_BeginTask[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Parent", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"bAddToTaskGroup", VbcOperandRole::Const, VbcOperandKind::Bool, false, false, false},
	{"OnYield", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_CallTask[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Parent", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Callee", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Arguments", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
};

constexpr VbcOperandDesc kVbcOperands_EndTask[] = {
	{"Write", VbcOperandRole::ClobberDef, VbcOperandKind::Register, false, true, false},
	{"Switch", VbcOperandRole::ClobberDef, VbcOperandKind::Register, false, true, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Which", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Signal", VbcOperandRole::Use, VbcOperandKind::Value, false, true, false},
};

constexpr VbcOperandDesc kVbcOperands_Yield[] = {
	{"ResumeOffset", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewSemaphore[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_WaitSemaphore[] = {
	{"Source", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Count", VbcOperandRole::Const, VbcOperandKind::I32, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Call[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Callee", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Arguments", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
	{"NamedArguments", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, true, false, false},
	{"NamedArgumentValues", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
	{"bCalleeYields", VbcOperandRole::Const, VbcOperandKind::Bool, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_CallWithSelf[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Callee", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Self", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Arguments", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
	{"NamedArguments", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, true, false, false},
	{"NamedArgumentValues", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
	{"bCalleeYields", VbcOperandRole::Const, VbcOperandKind::Bool, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Return[] = {
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_ReturnTrailed[] = {
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewRef[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Domain", VbcOperandRole::Use, VbcOperandKind::Value, false, true, false},
};

constexpr VbcOperandDesc kVbcOperands_NewPersistentOrSessionWeakMapRef[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_RefGet[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Ref", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_RefSet[] = {
	{"Ref", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_RefSetLive[] = {
	{"Ref", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Task", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_RefCallDomain[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Ref", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Argument", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Freeze[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_FreezeIfAccessor[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Melt[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Length[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Container", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_LengthWithEffects[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Container", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_CallSet[] = {
	{"Container", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Index", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"ValueToSet", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_CallSetLive[] = {
	{"Container", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Index", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"ValueToSet", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Task", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewArray[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Values", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewMutableArray[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Values", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewMutableArrayWithCapacity[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Size", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_ArrayAdd[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Container", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"ValueToAdd", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"bTransactional", VbcOperandRole::Const, VbcOperandKind::Bool, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_InPlaceMakeImmutable[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Container", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewOption[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewUnionVariant[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Tag", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Payload", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_GetUnionVariantPayload[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Source", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_GetUnionVariantTag[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Source", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewMap[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Keys", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
	{"Values", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
};

constexpr VbcOperandDesc kVbcOperands_MapKey[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Map", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Index", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_MapValue[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Map", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Index", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewClass[] = {
	{"ClassDest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"ArchetypeDest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"ConstructorDest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"BlocksDest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Package", VbcOperandRole::Immediate, VbcOperandKind::CellVPackage, false, false, false},
	{"RelativePath", VbcOperandRole::Immediate, VbcOperandKind::CellVArray, false, false, false},
	{"ClassName", VbcOperandRole::Immediate, VbcOperandKind::CellVArray, false, false, false},
	{"AttributeIndices", VbcOperandRole::Immediate, VbcOperandKind::ValueImm, true, false, false},
	{"Attributes", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
	{"ImportStruct", VbcOperandRole::Immediate, VbcOperandKind::ValueImm, false, true, false},
	{"Inherited", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
	{"Archetype", VbcOperandRole::Immediate, VbcOperandKind::CellVArchetype, false, false, false},
	{"ConstructorBody", VbcOperandRole::Immediate, VbcOperandKind::CellVProcedure, false, true, false},
	{"Blocks", VbcOperandRole::Immediate, VbcOperandKind::CellVProcedure, false, true, false},
	{"bNativeBound", VbcOperandRole::Const, VbcOperandKind::Bool, false, false, false},
	{"ClassKind", VbcOperandRole::Const, VbcOperandKind::EnumClassKind, false, false, false},
	{"Flags", VbcOperandRole::Const, VbcOperandKind::EnumClassFlags, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_BindNativeClass[] = {
	{"Class", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"bImported", VbcOperandRole::Const, VbcOperandKind::Bool, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_ConstructNativeDefaultObject[] = {
	{"Class", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_LoadImport[] = {
	{"Class", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"ImportPath", VbcOperandRole::Const, VbcOperandKind::AssetPath, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_JumpIfDefaultSubObject[] = {
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"OnDefaultSubObject", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_BeginModule[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Package", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"ModuleName", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_EndModule[] = {
	{"Module", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_EndModuleData[] = {
	{"FieldName", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewObject[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Archetype", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Class", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"CachedClass", VbcOperandRole::Const, VbcOperandKind::ClassRefIc, false, false, true},
	{"EmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_NewObjectICClass[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Archetype", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Class", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"CachedClass", VbcOperandRole::Const, VbcOperandKind::ClassRefIc, false, false, true},
	{"EmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_LoadField[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"EmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"ICPayload", VbcOperandRole::Const, VbcOperandKind::U64, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_LoadFieldICOffset[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"EmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"ICPayload", VbcOperandRole::Const, VbcOperandKind::U64, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_LoadFieldICConstant[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"EmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"ICPayload", VbcOperandRole::Const, VbcOperandKind::U64, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_LoadFieldICFunction[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"EmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"ICPayload", VbcOperandRole::Const, VbcOperandKind::U64, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_LoadFieldICNativeFunction[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"EmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"ICPayload", VbcOperandRole::Const, VbcOperandKind::U64, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_LoadFieldICAccessor[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"EmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"ICPayload", VbcOperandRole::Const, VbcOperandKind::U64, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_LoadFieldFromSuper[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Scope", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Self", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_CreateField[] = {
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Token", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
	{"SourceEmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"FieldIndex", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"NextEmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_CreateFieldICValueObjectConstant[] = {
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Token", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
	{"SourceEmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"FieldIndex", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"NextEmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_CreateFieldICValueObjectField[] = {
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Token", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
	{"SourceEmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"FieldIndex", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"NextEmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_CreateFieldICNativeStruct[] = {
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Token", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
	{"SourceEmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"FieldIndex", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"NextEmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_CreateFieldICUObject[] = {
	{"LeniencyIndicator", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Token", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"OnFailure", VbcOperandRole::Jump, VbcOperandKind::Label, false, false, false},
	{"SourceEmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"FieldIndex", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
	{"NextEmergentTypeOffset", VbcOperandRole::Const, VbcOperandKind::U32, false, false, true},
};

constexpr VbcOperandDesc kVbcOperands_UnifyField[] = {
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_InitializeVar[] = {
	{"TokenDest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Token", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"ValueDomain", VbcOperandRole::Use, VbcOperandKind::Value, false, true, false},
	{"bCheckIfVariableAllocationIsAllowed", VbcOperandRole::Const, VbcOperandKind::Bool, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_SetField[] = {
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_SetFieldLive[] = {
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Name", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"Value", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Task", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_UnifyNativeObject[] = {
	{"Token", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_UnwrapNativeConstructorWrapper[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Object", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewScope[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"ParentScope", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Captures", VbcOperandRole::Use, VbcOperandKind::Value, true, false, false},
};

constexpr VbcOperandDesc kVbcOperands_NewFunction[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Procedure", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Self", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"ParentScope", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_LoadParentScope[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Scope", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_LoadCapture[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Scope", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"Index", VbcOperandRole::Const, VbcOperandKind::U32, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_BeginProfileBlock[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_EndProfileBlock[] = {
	{"WallTimeStart", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"UserTag", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"SnippetPath", VbcOperandRole::Immediate, VbcOperandKind::CellVUniqueString, false, false, false},
	{"BeginRow", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"BeginColumn", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"EndRow", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"EndColumn", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_LoadConstructor[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"Class", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Neq[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Lt[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Lte[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Gt[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

constexpr VbcOperandDesc kVbcOperands_Gte[] = {
	{"Dest", VbcOperandRole::UnifyDef, VbcOperandKind::Register, false, false, false},
	{"LeftSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
	{"RightSource", VbcOperandRole::Use, VbcOperandKind::Value, false, false, false},
};

struct VbcOpDesc {
	const char *name;
	bool emitted;
	bool may_park;
	bool yields;
	const VbcOperandDesc *operands;
	int32_t operand_count;
};

constexpr VbcOpDesc kVbcOps[kVbcOpCount] = {
	{"Add", true, true, false, kVbcOperands_Add, 3},
	{"Sub", true, true, false, kVbcOperands_Sub, 3},
	{"Mul", true, true, false, kVbcOperands_Mul, 3},
	{"Div", true, true, false, kVbcOperands_Div, 3},
	{"Mod", false, true, false, kVbcOperands_Mod, 3},
	{"CanFastAppendToArrayFastFail", true, true, false, kVbcOperands_CanFastAppendToArrayFastFail, 4},
	{"FastAppendToArray", true, true, false, kVbcOperands_FastAppendToArray, 2},
	{"MutableAdd", false, true, false, kVbcOperands_MutableAdd, 3},
	{"Neg", true, true, false, kVbcOperands_Neg, 2},
	{"Query", true, true, false, kVbcOperands_Query, 2},
	{"Err", false, false, false, nullptr, 0},
	{"Tracepoint", false, false, false, kVbcOperands_Tracepoint, 1},
	{"Move", true, false, false, kVbcOperands_Move, 2},
	{"MoveTrailed", true, false, false, kVbcOperands_MoveTrailed, 2},
	{"MoveNonComparable", true, false, false, kVbcOperands_MoveNonComparable, 2},
	{"Reset", true, false, false, kVbcOperands_Reset, 2},
	{"ResetNonTrailed", true, false, false, kVbcOperands_ResetNonTrailed, 2},
	{"Jump", true, false, false, kVbcOperands_Jump, 1},
	{"JumpIfInitialized", true, false, false, kVbcOperands_JumpIfInitialized, 2},
	{"Switch", true, false, false, kVbcOperands_Switch, 2},
	{"LtFastFail", true, true, false, kVbcOperands_LtFastFail, 5},
	{"LteFastFail", true, true, false, kVbcOperands_LteFastFail, 5},
	{"GtFastFail", true, true, false, kVbcOperands_GtFastFail, 5},
	{"GteFastFail", true, true, false, kVbcOperands_GteFastFail, 5},
	{"EqFastFail", true, true, false, kVbcOperands_EqFastFail, 5},
	{"NeqFastFail", true, true, false, kVbcOperands_NeqFastFail, 5},
	{"ArrayIndexFastFail", true, true, false, kVbcOperands_ArrayIndexFastFail, 5},
	{"TypeCastFastFail", true, true, false, kVbcOperands_TypeCastFastFail, 5},
	{"QueryFastFail", true, true, false, kVbcOperands_QueryFastFail, 4},
	{"EndFastFailureContext", true, false, false, kVbcOperands_EndFastFailureContext, 3},
	{"BeginFailureContext", true, false, false, kVbcOperands_BeginFailureContext, 2},
	{"EndFailureContext", true, false, false, kVbcOperands_EndFailureContext, 2},
	{"SelfTask", true, false, false, kVbcOperands_SelfTask, 1},
	{"BeginTask", true, false, false, kVbcOperands_BeginTask, 4},
	{"CallTask", true, false, false, kVbcOperands_CallTask, 4},
	{"EndTask", true, false, true, kVbcOperands_EndTask, 5},
	{"BeginAwait", true, true, false, nullptr, 0},
	{"AwaitSuccess", true, true, false, nullptr, 0},
	{"EndAwait", true, true, false, nullptr, 0},
	{"BeginBatch", true, true, false, nullptr, 0},
	{"EndBatch", true, true, false, nullptr, 0},
	{"Yield", true, false, true, kVbcOperands_Yield, 1},
	{"NewSemaphore", true, false, false, kVbcOperands_NewSemaphore, 1},
	{"WaitSemaphore", true, false, true, kVbcOperands_WaitSemaphore, 2},
	{"Call", true, true, false, kVbcOperands_Call, 6},
	{"CallWithSelf", true, true, false, kVbcOperands_CallWithSelf, 7},
	{"Return", true, false, false, kVbcOperands_Return, 1},
	{"ReturnTrailed", true, false, false, kVbcOperands_ReturnTrailed, 1},
	{"ResumeUnwind", true, false, false, nullptr, 0},
	{"NewRef", true, false, false, kVbcOperands_NewRef, 2},
	{"NewPersistentOrSessionWeakMapRef", true, false, false, kVbcOperands_NewPersistentOrSessionWeakMapRef, 1},
	{"RefGet", true, true, false, kVbcOperands_RefGet, 2},
	{"RefSet", true, true, false, kVbcOperands_RefSet, 2},
	{"RefSetLive", true, true, false, kVbcOperands_RefSetLive, 3},
	{"RefCallDomain", true, true, false, kVbcOperands_RefCallDomain, 3},
	{"Freeze", true, true, false, kVbcOperands_Freeze, 2},
	{"FreezeIfAccessor", true, true, false, kVbcOperands_FreezeIfAccessor, 2},
	{"Melt", true, true, false, kVbcOperands_Melt, 2},
	{"Length", true, true, false, kVbcOperands_Length, 2},
	{"LengthWithEffects", true, true, false, kVbcOperands_LengthWithEffects, 2},
	{"CallSet", true, true, false, kVbcOperands_CallSet, 3},
	{"CallSetLive", true, true, false, kVbcOperands_CallSetLive, 4},
	{"NewArray", true, true, false, kVbcOperands_NewArray, 2},
	{"NewMutableArray", true, true, false, kVbcOperands_NewMutableArray, 2},
	{"NewMutableArrayWithCapacity", false, true, false, kVbcOperands_NewMutableArrayWithCapacity, 2},
	{"ArrayAdd", true, true, false, kVbcOperands_ArrayAdd, 4},
	{"InPlaceMakeImmutable", true, true, false, kVbcOperands_InPlaceMakeImmutable, 2},
	{"NewOption", true, true, false, kVbcOperands_NewOption, 2},
	{"NewUnionVariant", true, true, false, kVbcOperands_NewUnionVariant, 3},
	{"GetUnionVariantPayload", true, true, false, kVbcOperands_GetUnionVariantPayload, 2},
	{"GetUnionVariantTag", true, true, false, kVbcOperands_GetUnionVariantTag, 2},
	{"NewMap", true, true, false, kVbcOperands_NewMap, 3},
	{"MapKey", true, true, false, kVbcOperands_MapKey, 3},
	{"MapValue", true, true, false, kVbcOperands_MapValue, 3},
	{"NewClass", true, true, false, kVbcOperands_NewClass, 17},
	{"BindNativeClass", true, true, false, kVbcOperands_BindNativeClass, 2},
	{"ConstructNativeDefaultObject", true, false, false, kVbcOperands_ConstructNativeDefaultObject, 1},
	{"LoadImport", true, false, true, kVbcOperands_LoadImport, 2},
	{"JumpIfDefaultSubObject", true, false, false, kVbcOperands_JumpIfDefaultSubObject, 2},
	{"BeginModule", true, false, false, kVbcOperands_BeginModule, 3},
	{"EndModule", true, false, false, kVbcOperands_EndModule, 1},
	{"EndModuleData", true, true, false, kVbcOperands_EndModuleData, 2},
	{"NewObject", true, true, false, kVbcOperands_NewObject, 5},
	{"NewObjectICClass", false, true, false, kVbcOperands_NewObjectICClass, 5},
	{"LoadField", true, true, false, kVbcOperands_LoadField, 5},
	{"LoadFieldICOffset", false, true, false, kVbcOperands_LoadFieldICOffset, 5},
	{"LoadFieldICConstant", false, true, false, kVbcOperands_LoadFieldICConstant, 5},
	{"LoadFieldICFunction", false, true, false, kVbcOperands_LoadFieldICFunction, 5},
	{"LoadFieldICNativeFunction", false, true, false, kVbcOperands_LoadFieldICNativeFunction, 5},
	{"LoadFieldICAccessor", false, true, false, kVbcOperands_LoadFieldICAccessor, 5},
	{"LoadFieldFromSuper", true, true, false, kVbcOperands_LoadFieldFromSuper, 4},
	{"CreateField", true, true, false, kVbcOperands_CreateField, 8},
	{"CreateFieldICValueObjectConstant", false, true, false, kVbcOperands_CreateFieldICValueObjectConstant, 8},
	{"CreateFieldICValueObjectField", false, true, false, kVbcOperands_CreateFieldICValueObjectField, 8},
	{"CreateFieldICNativeStruct", false, true, false, kVbcOperands_CreateFieldICNativeStruct, 8},
	{"CreateFieldICUObject", false, true, false, kVbcOperands_CreateFieldICUObject, 8},
	{"UnifyField", true, true, false, kVbcOperands_UnifyField, 3},
	{"InitializeVar", true, true, false, kVbcOperands_InitializeVar, 7},
	{"SetField", true, true, false, kVbcOperands_SetField, 3},
	{"SetFieldLive", true, true, false, kVbcOperands_SetFieldLive, 4},
	{"UnifyNativeObject", true, true, false, kVbcOperands_UnifyNativeObject, 2},
	{"UnwrapNativeConstructorWrapper", true, true, false, kVbcOperands_UnwrapNativeConstructorWrapper, 2},
	{"NewScope", true, true, false, kVbcOperands_NewScope, 3},
	{"NewFunction", true, true, false, kVbcOperands_NewFunction, 4},
	{"LoadParentScope", true, true, false, kVbcOperands_LoadParentScope, 2},
	{"LoadCapture", true, true, false, kVbcOperands_LoadCapture, 3},
	{"BeginProfileBlock", true, true, false, kVbcOperands_BeginProfileBlock, 1},
	{"EndProfileBlock", true, true, false, kVbcOperands_EndProfileBlock, 7},
	{"LoadConstructor", true, true, false, kVbcOperands_LoadConstructor, 2},
	{"Neq", true, true, false, kVbcOperands_Neq, 3},
	{"Lt", true, true, false, kVbcOperands_Lt, 3},
	{"Lte", true, true, false, kVbcOperands_Lte, 3},
	{"Gt", true, true, false, kVbcOperands_Gt, 3},
	{"Gte", true, true, false, kVbcOperands_Gte, 3},
};

// The same digest `gen_vbc_ops.py --digest` prints. format.md §2.1 requires a reader to
// refuse a .vbc file stamped with any other -- this is what an engine bump changing
// the op set is caught by.
constexpr char kVbcOpsSchemaDigest[] = "0c249c8bd5daf1537da5b945fcf2a62b84d2348b51501b524ac616ee13716c9e";

} // namespace vbc
