/* Generated by tools/gen_abi_layout.py from clang's layout of include/verse_host_abi.h. Do not
 * edit by hand: rerun it after changing one of these structs, which is an ABI major bump.
 *
 * The layout of every struct the ABI hands over as an array, pinned. An element's size is the
 * stride the other side indexes by, so a change that is not a major bump is a build failure here in
 * whichever binary compiles first -- and VH_LAYOUT_DIGEST is what vh_init compares, so two binaries
 * that each compiled cleanly against different layouts are refused by name rather than read as
 * corruption. Included by verse_host_abi.h; nothing else includes it.
 */
#ifndef VERSE_HOST_ABI_LAYOUT_H
#define VERSE_HOST_ABI_LAYOUT_H

#ifdef __cplusplus
#	define VH_STATIC_ASSERT(Condition, Message) static_assert(Condition, Message)
#	define VH_ALIGNOF(Type) alignof(Type)
#	define VH_CONSTEXPR constexpr
#else
#	define VH_STATIC_ASSERT(Condition, Message) _Static_assert(Condition, Message)
#	define VH_ALIGNOF(Type) _Alignof(Type)
#	define VH_CONSTEXPR
#endif

/* MSVC's C++ offsetof is a reinterpret_cast, which a constant expression may not contain. */
#if defined(_MSC_VER) && !defined(__clang__) && defined(__cplusplus)
#	define VH_OFFSETOF(Type, Field) __builtin_offsetof(Type, Field)
#else
#	define VH_OFFSETOF(Type, Field) offsetof(Type, Field)
#endif

/* The three layouts these structs have: 64-bit pointers; 32-bit pointers with an 8-byte-aligned
 * int64 and double (wasm32, Windows x86, ARM32); and 32-bit pointers with a 4-byte-aligned one, the
 * i386 System V ABI of Linux and Android x86. vh_value holds an int64, so its alignment is the one
 * that tells the last two apart. */
#define VH_LAYOUT(P8, P4A8, P4A4) \
	(sizeof(void*) == 8 ? (size_t)(P8) : VH_ALIGNOF(vh_value) == 8 ? (size_t)(P4A8) : (size_t)(P4A4))

VH_STATIC_ASSERT(sizeof(vh_value) == VH_LAYOUT(24, 16, 16), "vh_value changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, Type) == VH_LAYOUT(0, 0, 0), "vh_value::Type moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, VariantTag) == VH_LAYOUT(4, 4, 4), "vh_value::VariantTag moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, Logic) == VH_LAYOUT(8, 8, 8), "vh_value::Logic moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, Int) == VH_LAYOUT(8, 8, 8), "vh_value::Int moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, Float) == VH_LAYOUT(8, 8, 8), "vh_value::Float moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, Char) == VH_LAYOUT(8, 8, 8), "vh_value::Char moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, Ref) == VH_LAYOUT(8, 8, 8), "vh_value::Ref moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, String) == VH_LAYOUT(8, 8, 8), "vh_value::String moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, Seq) == VH_LAYOUT(8, 8, 8), "vh_value::Seq moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, Map) == VH_LAYOUT(8, 8, 8), "vh_value::Map moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_value, Option) == VH_LAYOUT(8, 8, 8), "vh_value::Option moved");

VH_STATIC_ASSERT(sizeof(vh_pair) == VH_LAYOUT(48, 32, 32), "vh_pair changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_pair, Key) == VH_LAYOUT(0, 0, 0), "vh_pair::Key moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_pair, Value) == VH_LAYOUT(24, 16, 16), "vh_pair::Value moved");

VH_STATIC_ASSERT(sizeof(vh_source_file) == VH_LAYOUT(16, 8, 8), "vh_source_file changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_source_file, PathUtf8) == VH_LAYOUT(0, 0, 0), "vh_source_file::PathUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_source_file, ModulePathUtf8) == VH_LAYOUT(8, 4, 4), "vh_source_file::ModulePathUtf8 moved");

VH_STATIC_ASSERT(sizeof(vh_binding_class) == VH_LAYOUT(48, 24, 24), "vh_binding_class changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_binding_class, GodotClassUtf8) == VH_LAYOUT(0, 0, 0), "vh_binding_class::GodotClassUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_binding_class, GodotClassLen) == VH_LAYOUT(8, 4, 4), "vh_binding_class::GodotClassLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_binding_class, ScriptClassUtf8) == VH_LAYOUT(16, 8, 8), "vh_binding_class::ScriptClassUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_binding_class, ScriptClassLen) == VH_LAYOUT(24, 12, 12), "vh_binding_class::ScriptClassLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_binding_class, VerseClassUtf8) == VH_LAYOUT(32, 16, 16), "vh_binding_class::VerseClassUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_binding_class, VerseClassLen) == VH_LAYOUT(40, 20, 20), "vh_binding_class::VerseClassLen moved");

VH_STATIC_ASSERT(sizeof(vh_param_desc) == VH_LAYOUT(40, 32, 32), "vh_param_desc changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_param_desc, NameUtf8) == VH_LAYOUT(0, 0, 0), "vh_param_desc::NameUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_param_desc, NameLen) == VH_LAYOUT(8, 4, 4), "vh_param_desc::NameLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_param_desc, Type) == VH_LAYOUT(12, 8, 8), "vh_param_desc::Type moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_param_desc, VariantTag) == VH_LAYOUT(16, 12, 12), "vh_param_desc::VariantTag moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_param_desc, HasDefault) == VH_LAYOUT(20, 16, 16), "vh_param_desc::HasDefault moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_param_desc, ClassUtf8) == VH_LAYOUT(24, 20, 20), "vh_param_desc::ClassUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_param_desc, ClassLen) == VH_LAYOUT(32, 24, 24), "vh_param_desc::ClassLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_param_desc, ClassKind) == VH_LAYOUT(36, 28, 28), "vh_param_desc::ClassKind moved");

VH_STATIC_ASSERT(sizeof(vh_method_desc) == VH_LAYOUT(104, 72, 72), "vh_method_desc changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, NameUtf8) == VH_LAYOUT(0, 0, 0), "vh_method_desc::NameUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, NameLen) == VH_LAYOUT(8, 4, 4), "vh_method_desc::NameLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, DecoratedUtf8) == VH_LAYOUT(16, 8, 8), "vh_method_desc::DecoratedUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, DecoratedLen) == VH_LAYOUT(24, 12, 12), "vh_method_desc::DecoratedLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, Params) == VH_LAYOUT(32, 16, 16), "vh_method_desc::Params moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, ParamCount) == VH_LAYOUT(40, 20, 20), "vh_method_desc::ParamCount moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, RequiredParamCount) == VH_LAYOUT(44, 24, 24), "vh_method_desc::RequiredParamCount moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, ResultType) == VH_LAYOUT(48, 28, 28), "vh_method_desc::ResultType moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, ResultVariantTag) == VH_LAYOUT(52, 32, 32), "vh_method_desc::ResultVariantTag moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, ResultClassUtf8) == VH_LAYOUT(56, 36, 36), "vh_method_desc::ResultClassUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, ResultClassLen) == VH_LAYOUT(64, 40, 40), "vh_method_desc::ResultClassLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, ResultClassKind) == VH_LAYOUT(68, 44, 44), "vh_method_desc::ResultClassKind moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, CanFail) == VH_LAYOUT(72, 48, 48), "vh_method_desc::CanFail moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, Suspends) == VH_LAYOUT(76, 52, 52), "vh_method_desc::Suspends moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, GodotVirtualUtf8) == VH_LAYOUT(80, 56, 56), "vh_method_desc::GodotVirtualUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, GodotVirtualLen) == VH_LAYOUT(88, 60, 60), "vh_method_desc::GodotVirtualLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, Line) == VH_LAYOUT(92, 64, 64), "vh_method_desc::Line moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_method_desc, Column) == VH_LAYOUT(96, 68, 68), "vh_method_desc::Column moved");

VH_STATIC_ASSERT(sizeof(vh_signal_desc) == VH_LAYOUT(56, 36, 36), "vh_signal_desc changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_signal_desc, NameUtf8) == VH_LAYOUT(0, 0, 0), "vh_signal_desc::NameUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_signal_desc, NameLen) == VH_LAYOUT(8, 4, 4), "vh_signal_desc::NameLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_signal_desc, Args) == VH_LAYOUT(16, 8, 8), "vh_signal_desc::Args moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_signal_desc, ArgCount) == VH_LAYOUT(24, 12, 12), "vh_signal_desc::ArgCount moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_signal_desc, Line) == VH_LAYOUT(28, 16, 16), "vh_signal_desc::Line moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_signal_desc, Column) == VH_LAYOUT(32, 20, 20), "vh_signal_desc::Column moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_signal_desc, Reject) == VH_LAYOUT(36, 24, 24), "vh_signal_desc::Reject moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_signal_desc, RejectDetailUtf8) == VH_LAYOUT(40, 28, 28), "vh_signal_desc::RejectDetailUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_signal_desc, RejectDetailLen) == VH_LAYOUT(48, 32, 32), "vh_signal_desc::RejectDetailLen moved");

VH_STATIC_ASSERT(sizeof(vh_rpc_desc) == VH_LAYOUT(56, 44, 44), "vh_rpc_desc changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, NameUtf8) == VH_LAYOUT(0, 0, 0), "vh_rpc_desc::NameUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, NameLen) == VH_LAYOUT(8, 4, 4), "vh_rpc_desc::NameLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, RpcMode) == VH_LAYOUT(12, 8, 8), "vh_rpc_desc::RpcMode moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, CallLocal) == VH_LAYOUT(16, 12, 12), "vh_rpc_desc::CallLocal moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, TransferMode) == VH_LAYOUT(20, 16, 16), "vh_rpc_desc::TransferMode moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, Channel) == VH_LAYOUT(24, 20, 20), "vh_rpc_desc::Channel moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, Line) == VH_LAYOUT(28, 24, 24), "vh_rpc_desc::Line moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, Column) == VH_LAYOUT(32, 28, 28), "vh_rpc_desc::Column moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, Reject) == VH_LAYOUT(36, 32, 32), "vh_rpc_desc::Reject moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, RejectDetailUtf8) == VH_LAYOUT(40, 36, 36), "vh_rpc_desc::RejectDetailUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_rpc_desc, RejectDetailLen) == VH_LAYOUT(48, 40, 40), "vh_rpc_desc::RejectDetailLen moved");

VH_STATIC_ASSERT(sizeof(vh_static_desc) == VH_LAYOUT(48, 40, 36), "vh_static_desc changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_static_desc, NameUtf8) == VH_LAYOUT(0, 0, 0), "vh_static_desc::NameUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_static_desc, NameLen) == VH_LAYOUT(8, 4, 4), "vh_static_desc::NameLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_static_desc, IsFunction) == VH_LAYOUT(12, 8, 8), "vh_static_desc::IsFunction moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_static_desc, Value) == VH_LAYOUT(16, 16, 12), "vh_static_desc::Value moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_static_desc, Line) == VH_LAYOUT(40, 32, 28), "vh_static_desc::Line moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_static_desc, Column) == VH_LAYOUT(44, 36, 32), "vh_static_desc::Column moved");

VH_STATIC_ASSERT(sizeof(vh_export_desc) == VH_LAYOUT(120, 96, 92), "vh_export_desc changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, NameUtf8) == VH_LAYOUT(0, 0, 0), "vh_export_desc::NameUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, NameLen) == VH_LAYOUT(8, 4, 4), "vh_export_desc::NameLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, Type) == VH_LAYOUT(12, 8, 8), "vh_export_desc::Type moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, VariantTag) == VH_LAYOUT(16, 12, 12), "vh_export_desc::VariantTag moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, ElementVariantTag) == VH_LAYOUT(20, 16, 16), "vh_export_desc::ElementVariantTag moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, IsVar) == VH_LAYOUT(24, 20, 20), "vh_export_desc::IsVar moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, Hint) == VH_LAYOUT(28, 24, 24), "vh_export_desc::Hint moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, HintStringUtf8) == VH_LAYOUT(32, 28, 28), "vh_export_desc::HintStringUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, HintStringLen) == VH_LAYOUT(40, 32, 32), "vh_export_desc::HintStringLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, NativeClassUtf8) == VH_LAYOUT(48, 36, 36), "vh_export_desc::NativeClassUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, NativeClassLen) == VH_LAYOUT(56, 40, 40), "vh_export_desc::NativeClassLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, RangeMin) == VH_LAYOUT(64, 48, 44), "vh_export_desc::RangeMin moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, RangeMax) == VH_LAYOUT(72, 56, 52), "vh_export_desc::RangeMax moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, HasRangeMin) == VH_LAYOUT(80, 64, 60), "vh_export_desc::HasRangeMin moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, HasRangeMax) == VH_LAYOUT(84, 68, 64), "vh_export_desc::HasRangeMax moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, GroupKind) == VH_LAYOUT(88, 72, 68), "vh_export_desc::GroupKind moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, GroupNameUtf8) == VH_LAYOUT(96, 76, 72), "vh_export_desc::GroupNameUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, GroupNameLen) == VH_LAYOUT(104, 80, 76), "vh_export_desc::GroupNameLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, Line) == VH_LAYOUT(108, 84, 80), "vh_export_desc::Line moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, Column) == VH_LAYOUT(112, 88, 84), "vh_export_desc::Column moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_export_desc, Reject) == VH_LAYOUT(116, 92, 88), "vh_export_desc::Reject moved");

VH_STATIC_ASSERT(sizeof(vh_complete_item) == VH_LAYOUT(104, 68, 68), "vh_complete_item changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, NameUtf8) == VH_LAYOUT(0, 0, 0), "vh_complete_item::NameUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, NameLen) == VH_LAYOUT(8, 4, 4), "vh_complete_item::NameLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, TypeUtf8) == VH_LAYOUT(16, 8, 8), "vh_complete_item::TypeUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, TypeLen) == VH_LAYOUT(24, 12, 12), "vh_complete_item::TypeLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, OwnerUtf8) == VH_LAYOUT(32, 16, 16), "vh_complete_item::OwnerUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, OwnerLen) == VH_LAYOUT(40, 20, 20), "vh_complete_item::OwnerLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, PathUtf8) == VH_LAYOUT(48, 24, 24), "vh_complete_item::PathUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, PathLen) == VH_LAYOUT(56, 28, 28), "vh_complete_item::PathLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, Line) == VH_LAYOUT(60, 32, 32), "vh_complete_item::Line moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, Kind) == VH_LAYOUT(64, 36, 36), "vh_complete_item::Kind moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, IsVar) == VH_LAYOUT(68, 40, 40), "vh_complete_item::IsVar moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, ParamCount) == VH_LAYOUT(72, 44, 44), "vh_complete_item::ParamCount moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, SignatureUtf8) == VH_LAYOUT(80, 48, 48), "vh_complete_item::SignatureUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, SignatureLen) == VH_LAYOUT(88, 52, 52), "vh_complete_item::SignatureLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, IsOverridable) == VH_LAYOUT(92, 56, 56), "vh_complete_item::IsOverridable moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, OwnerDistance) == VH_LAYOUT(96, 60, 60), "vh_complete_item::OwnerDistance moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_complete_item, IsNamed) == VH_LAYOUT(100, 64, 64), "vh_complete_item::IsNamed moved");

VH_STATIC_ASSERT(sizeof(vh_module_ref) == VH_LAYOUT(16, 8, 8), "vh_module_ref changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_module_ref, PathUtf8) == VH_LAYOUT(0, 0, 0), "vh_module_ref::PathUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_module_ref, PathLen) == VH_LAYOUT(8, 4, 4), "vh_module_ref::PathLen moved");

VH_STATIC_ASSERT(sizeof(vh_stack_frame) == VH_LAYOUT(40, 24, 24), "vh_stack_frame changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_stack_frame, FunctionUtf8) == VH_LAYOUT(0, 0, 0), "vh_stack_frame::FunctionUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_stack_frame, FunctionLen) == VH_LAYOUT(8, 4, 4), "vh_stack_frame::FunctionLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_stack_frame, PathUtf8) == VH_LAYOUT(16, 8, 8), "vh_stack_frame::PathUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_stack_frame, PathLen) == VH_LAYOUT(24, 12, 12), "vh_stack_frame::PathLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_stack_frame, Line) == VH_LAYOUT(28, 16, 16), "vh_stack_frame::Line moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_stack_frame, Column) == VH_LAYOUT(32, 20, 20), "vh_stack_frame::Column moved");

VH_STATIC_ASSERT(sizeof(vh_debug_value) == VH_LAYOUT(48, 24, 24), "vh_debug_value changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_debug_value, StructSize) == VH_LAYOUT(0, 0, 0), "vh_debug_value::StructSize moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_debug_value, NameUtf8) == VH_LAYOUT(8, 4, 4), "vh_debug_value::NameUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_debug_value, NameLen) == VH_LAYOUT(16, 8, 8), "vh_debug_value::NameLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_debug_value, Value) == VH_LAYOUT(24, 12, 12), "vh_debug_value::Value moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_debug_value, RenderedUtf8) == VH_LAYOUT(32, 16, 16), "vh_debug_value::RenderedUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_debug_value, RenderedLen) == VH_LAYOUT(40, 20, 20), "vh_debug_value::RenderedLen moved");

VH_STATIC_ASSERT(sizeof(vh_profile_row) == VH_LAYOUT(48, 40, 36), "vh_profile_row changed size: its stride is the ABI's, so that is a major bump");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_profile_row, StructSize) == VH_LAYOUT(0, 0, 0), "vh_profile_row::StructSize moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_profile_row, SignatureUtf8) == VH_LAYOUT(8, 4, 4), "vh_profile_row::SignatureUtf8 moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_profile_row, SignatureLen) == VH_LAYOUT(16, 8, 8), "vh_profile_row::SignatureLen moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_profile_row, CallCount) == VH_LAYOUT(24, 16, 12), "vh_profile_row::CallCount moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_profile_row, TotalSeconds) == VH_LAYOUT(32, 24, 20), "vh_profile_row::TotalSeconds moved");
VH_STATIC_ASSERT(VH_OFFSETOF(vh_profile_row, SelfSeconds) == VH_LAYOUT(40, 32, 28), "vh_profile_row::SelfSeconds moved");

/* FNV-1a over every size and offset above, in order. It differs between the three layouts, which is
 * right: it is compared between two binaries on one machine, never across. */
static inline VH_CONSTEXPR uint32_t vh_layout_digest(void)
{
	const size_t Facts[] = {
		sizeof(vh_value),
		VH_OFFSETOF(vh_value, Type),
		VH_OFFSETOF(vh_value, VariantTag),
		VH_OFFSETOF(vh_value, Logic),
		VH_OFFSETOF(vh_value, Int),
		VH_OFFSETOF(vh_value, Float),
		VH_OFFSETOF(vh_value, Char),
		VH_OFFSETOF(vh_value, Ref),
		VH_OFFSETOF(vh_value, String),
		VH_OFFSETOF(vh_value, Seq),
		VH_OFFSETOF(vh_value, Map),
		VH_OFFSETOF(vh_value, Option),
		sizeof(vh_pair),
		VH_OFFSETOF(vh_pair, Key),
		VH_OFFSETOF(vh_pair, Value),
		sizeof(vh_source_file),
		VH_OFFSETOF(vh_source_file, PathUtf8),
		VH_OFFSETOF(vh_source_file, ModulePathUtf8),
		sizeof(vh_binding_class),
		VH_OFFSETOF(vh_binding_class, GodotClassUtf8),
		VH_OFFSETOF(vh_binding_class, GodotClassLen),
		VH_OFFSETOF(vh_binding_class, ScriptClassUtf8),
		VH_OFFSETOF(vh_binding_class, ScriptClassLen),
		VH_OFFSETOF(vh_binding_class, VerseClassUtf8),
		VH_OFFSETOF(vh_binding_class, VerseClassLen),
		sizeof(vh_param_desc),
		VH_OFFSETOF(vh_param_desc, NameUtf8),
		VH_OFFSETOF(vh_param_desc, NameLen),
		VH_OFFSETOF(vh_param_desc, Type),
		VH_OFFSETOF(vh_param_desc, VariantTag),
		VH_OFFSETOF(vh_param_desc, HasDefault),
		VH_OFFSETOF(vh_param_desc, ClassUtf8),
		VH_OFFSETOF(vh_param_desc, ClassLen),
		VH_OFFSETOF(vh_param_desc, ClassKind),
		sizeof(vh_method_desc),
		VH_OFFSETOF(vh_method_desc, NameUtf8),
		VH_OFFSETOF(vh_method_desc, NameLen),
		VH_OFFSETOF(vh_method_desc, DecoratedUtf8),
		VH_OFFSETOF(vh_method_desc, DecoratedLen),
		VH_OFFSETOF(vh_method_desc, Params),
		VH_OFFSETOF(vh_method_desc, ParamCount),
		VH_OFFSETOF(vh_method_desc, RequiredParamCount),
		VH_OFFSETOF(vh_method_desc, ResultType),
		VH_OFFSETOF(vh_method_desc, ResultVariantTag),
		VH_OFFSETOF(vh_method_desc, ResultClassUtf8),
		VH_OFFSETOF(vh_method_desc, ResultClassLen),
		VH_OFFSETOF(vh_method_desc, ResultClassKind),
		VH_OFFSETOF(vh_method_desc, CanFail),
		VH_OFFSETOF(vh_method_desc, Suspends),
		VH_OFFSETOF(vh_method_desc, GodotVirtualUtf8),
		VH_OFFSETOF(vh_method_desc, GodotVirtualLen),
		VH_OFFSETOF(vh_method_desc, Line),
		VH_OFFSETOF(vh_method_desc, Column),
		sizeof(vh_signal_desc),
		VH_OFFSETOF(vh_signal_desc, NameUtf8),
		VH_OFFSETOF(vh_signal_desc, NameLen),
		VH_OFFSETOF(vh_signal_desc, Args),
		VH_OFFSETOF(vh_signal_desc, ArgCount),
		VH_OFFSETOF(vh_signal_desc, Line),
		VH_OFFSETOF(vh_signal_desc, Column),
		VH_OFFSETOF(vh_signal_desc, Reject),
		VH_OFFSETOF(vh_signal_desc, RejectDetailUtf8),
		VH_OFFSETOF(vh_signal_desc, RejectDetailLen),
		sizeof(vh_rpc_desc),
		VH_OFFSETOF(vh_rpc_desc, NameUtf8),
		VH_OFFSETOF(vh_rpc_desc, NameLen),
		VH_OFFSETOF(vh_rpc_desc, RpcMode),
		VH_OFFSETOF(vh_rpc_desc, CallLocal),
		VH_OFFSETOF(vh_rpc_desc, TransferMode),
		VH_OFFSETOF(vh_rpc_desc, Channel),
		VH_OFFSETOF(vh_rpc_desc, Line),
		VH_OFFSETOF(vh_rpc_desc, Column),
		VH_OFFSETOF(vh_rpc_desc, Reject),
		VH_OFFSETOF(vh_rpc_desc, RejectDetailUtf8),
		VH_OFFSETOF(vh_rpc_desc, RejectDetailLen),
		sizeof(vh_static_desc),
		VH_OFFSETOF(vh_static_desc, NameUtf8),
		VH_OFFSETOF(vh_static_desc, NameLen),
		VH_OFFSETOF(vh_static_desc, IsFunction),
		VH_OFFSETOF(vh_static_desc, Value),
		VH_OFFSETOF(vh_static_desc, Line),
		VH_OFFSETOF(vh_static_desc, Column),
		sizeof(vh_export_desc),
		VH_OFFSETOF(vh_export_desc, NameUtf8),
		VH_OFFSETOF(vh_export_desc, NameLen),
		VH_OFFSETOF(vh_export_desc, Type),
		VH_OFFSETOF(vh_export_desc, VariantTag),
		VH_OFFSETOF(vh_export_desc, ElementVariantTag),
		VH_OFFSETOF(vh_export_desc, IsVar),
		VH_OFFSETOF(vh_export_desc, Hint),
		VH_OFFSETOF(vh_export_desc, HintStringUtf8),
		VH_OFFSETOF(vh_export_desc, HintStringLen),
		VH_OFFSETOF(vh_export_desc, NativeClassUtf8),
		VH_OFFSETOF(vh_export_desc, NativeClassLen),
		VH_OFFSETOF(vh_export_desc, RangeMin),
		VH_OFFSETOF(vh_export_desc, RangeMax),
		VH_OFFSETOF(vh_export_desc, HasRangeMin),
		VH_OFFSETOF(vh_export_desc, HasRangeMax),
		VH_OFFSETOF(vh_export_desc, GroupKind),
		VH_OFFSETOF(vh_export_desc, GroupNameUtf8),
		VH_OFFSETOF(vh_export_desc, GroupNameLen),
		VH_OFFSETOF(vh_export_desc, Line),
		VH_OFFSETOF(vh_export_desc, Column),
		VH_OFFSETOF(vh_export_desc, Reject),
		sizeof(vh_complete_item),
		VH_OFFSETOF(vh_complete_item, NameUtf8),
		VH_OFFSETOF(vh_complete_item, NameLen),
		VH_OFFSETOF(vh_complete_item, TypeUtf8),
		VH_OFFSETOF(vh_complete_item, TypeLen),
		VH_OFFSETOF(vh_complete_item, OwnerUtf8),
		VH_OFFSETOF(vh_complete_item, OwnerLen),
		VH_OFFSETOF(vh_complete_item, PathUtf8),
		VH_OFFSETOF(vh_complete_item, PathLen),
		VH_OFFSETOF(vh_complete_item, Line),
		VH_OFFSETOF(vh_complete_item, Kind),
		VH_OFFSETOF(vh_complete_item, IsVar),
		VH_OFFSETOF(vh_complete_item, ParamCount),
		VH_OFFSETOF(vh_complete_item, SignatureUtf8),
		VH_OFFSETOF(vh_complete_item, SignatureLen),
		VH_OFFSETOF(vh_complete_item, IsOverridable),
		VH_OFFSETOF(vh_complete_item, OwnerDistance),
		VH_OFFSETOF(vh_complete_item, IsNamed),
		sizeof(vh_module_ref),
		VH_OFFSETOF(vh_module_ref, PathUtf8),
		VH_OFFSETOF(vh_module_ref, PathLen),
		sizeof(vh_stack_frame),
		VH_OFFSETOF(vh_stack_frame, FunctionUtf8),
		VH_OFFSETOF(vh_stack_frame, FunctionLen),
		VH_OFFSETOF(vh_stack_frame, PathUtf8),
		VH_OFFSETOF(vh_stack_frame, PathLen),
		VH_OFFSETOF(vh_stack_frame, Line),
		VH_OFFSETOF(vh_stack_frame, Column),
		sizeof(vh_debug_value),
		VH_OFFSETOF(vh_debug_value, StructSize),
		VH_OFFSETOF(vh_debug_value, NameUtf8),
		VH_OFFSETOF(vh_debug_value, NameLen),
		VH_OFFSETOF(vh_debug_value, Value),
		VH_OFFSETOF(vh_debug_value, RenderedUtf8),
		VH_OFFSETOF(vh_debug_value, RenderedLen),
		sizeof(vh_profile_row),
		VH_OFFSETOF(vh_profile_row, StructSize),
		VH_OFFSETOF(vh_profile_row, SignatureUtf8),
		VH_OFFSETOF(vh_profile_row, SignatureLen),
		VH_OFFSETOF(vh_profile_row, CallCount),
		VH_OFFSETOF(vh_profile_row, TotalSeconds),
		VH_OFFSETOF(vh_profile_row, SelfSeconds)
	};
	uint32_t Hash = 2166136261u;
	for (size_t Index = 0; Index < sizeof(Facts) / sizeof(Facts[0]); ++Index)
	{
		Hash = (Hash ^ (uint32_t)Facts[Index]) * 16777619u;
	}
	return Hash;
}

#define VH_LAYOUT_DIGEST (vh_layout_digest())

#endif /* VERSE_HOST_ABI_LAYOUT_H */
