"""Validates docs/web-vm/ops.json and prints the digest a .vbc header carries.

    python tools/gen_vbc_ops.py                       # validate; one line per failure, exit 1 on any
    python tools/gen_vbc_ops.py --digest              # print the canonical SHA-256
    python tools/gen_vbc_ops.py --emit-cpp vm/vbc_ops.gen.h  # write the decoder tables

The digest is taken over the canonical form (sorted keys, no whitespace) so reformatting the file
does not change it and any change of fact does. The writer stamps it into every .vbc and a reader
refuses a file stamped with any other, which is what catches an engine bump that changed the op set.

--emit-cpp generates the same facts as a C++ header: an enum class of opcodes, and per-op constexpr
tables of what format.md §5.1 needs to decode one. It is the one way the writer's encoder and the
interpreter's decoder share a fact without sharing code (design §5), so it validates the schema
first and refuses to emit from an invalid one.
"""

import argparse
import hashlib
import json
import pathlib
import re
import sys

OPS_JSON = pathlib.Path(__file__).resolve().parent.parent / "docs" / "web-vm" / "ops.json"

CATEGORIES = {
    "arith", "failure", "move_control", "call", "task", "ref", "container", "object",
    "native_module", "inline_cache", "debug",
}
OP_KEYS = {"number", "name", "category", "emitted", "may_park", "yields", "captures", "operands"}
OPTIONAL_OP_KEYS = {"emitted_note"}
OPERAND_KEYS = {"name", "role", "kind", "variadic", "optional", "cache"}


def load(path=OPS_JSON):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def digest(schema):
    canonical = json.dumps(schema, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def validate(schema):
    errors = []
    roles = schema.get("operand_roles", {})
    kinds = schema.get("operand_kinds", {})
    enums = schema.get("enums", {})
    captures = schema.get("capture_flags", {})
    ops = schema.get("ops", [])

    width = schema.get("opcode_width_bits")
    if width != 16:
        errors.append(f"opcode_width_bits is {width}, expected 16")

    numbers = [op.get("number") for op in ops]
    if numbers != list(range(len(ops))):
        errors.append("op numbers are not 0..n-1 in file order")

    names = [op.get("name") for op in ops]
    if len(set(names)) != len(names):
        errors.append("op names are not unique")

    used_roles, used_kinds, used_captures = set(), set(), set()
    for op in ops:
        where = f"op {op.get('number')} {op.get('name')}"
        keys = set(op)
        if not OP_KEYS <= keys or keys - OP_KEYS - OPTIONAL_OP_KEYS:
            errors.append(f"{where}: keys {sorted(keys)}")
            continue
        if op["category"] not in CATEGORIES:
            errors.append(f"{where}: category {op['category']}")
        if op["category"] == "inline_cache" and op["emitted"]:
            errors.append(f"{where}: an inline-cache op marked emitted")
        if op["captures"] and not op["may_park"]:
            errors.append(f"{where}: captures without may_park")
        used_captures.update(op["captures"])
        for operand in op["operands"]:
            if set(operand) != OPERAND_KEYS:
                errors.append(f"{where}.{operand.get('name')}: keys {sorted(operand)}")
                continue
            used_roles.add(operand["role"])
            used_kinds.add(operand["kind"])
            kind = operand["kind"]
            if kind.startswith("enum:") and kind[5:] not in enums:
                errors.append(f"{where}.{operand['name']}: undefined {kind}")
            if kind.startswith("cell:") and kind[5:] not in schema.get("cell_types", []):
                errors.append(f"{where}.{operand['name']}: undeclared {kind}")

    for label, declared, used in (
        ("role", set(roles), used_roles),
        ("kind", set(kinds), used_kinds),
        ("capture flag", set(captures), used_captures),
    ):
        for name in sorted(used - declared):
            errors.append(f"{label} {name} used but not declared")
        for name in sorted(declared - used):
            errors.append(f"{label} {name} declared but not used")
    return errors


def _pascal(name):
    """"cell:VUniqueString" -> "CellVUniqueString", "value_imm" -> "ValueImm", "u64" -> "U64"."""
    parts = [p for p in re.split(r"[_:]", name) if p]
    return "".join(p[0].upper() + p[1:] for p in parts)


def _cpp_bool(value):
    return "true" if value else "false"


def _cpp_str(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def emit_cpp(schema):
    roles = list(schema["operand_roles"])
    kinds = list(schema["operand_kinds"])
    ops = schema["ops"]

    lines = []
    lines.append("// Generated by tools/gen_vbc_ops.py --emit-cpp from docs/web-vm/ops.json.")
    lines.append("// Do not hand-edit -- regenerate instead. See docs/web-vm/format.md §5.1.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace vbc {")
    lines.append("")
    lines.append("enum class VbcOperandRole : uint8_t {")
    for role in roles:
        lines.append(f"\t{_pascal(role)},")
    lines.append("};")
    lines.append("")
    lines.append("enum class VbcOperandKind : uint8_t {")
    for kind in kinds:
        lines.append(f"\t{_pascal(kind)},")
    lines.append("};")
    lines.append("")
    lines.append("struct VbcOperandDesc {")
    lines.append("\tconst char *name;")
    lines.append("\tVbcOperandRole role;")
    lines.append("\tVbcOperandKind kind;")
    lines.append("\tbool variadic;")
    lines.append("\tbool optional;")
    lines.append("\tbool cache;")
    lines.append("};")
    lines.append("")
    lines.append(f"enum class VbcOp : uint16_t {{")
    for op in ops:
        lines.append(f"\t{op['name']} = {op['number']},")
    lines.append("};")
    lines.append("")
    lines.append(f"constexpr int32_t kVbcOpCount = {len(ops)};")
    lines.append("")
    for op in ops:
        array_name = f"kVbcOperands_{op['name']}"
        if not op["operands"]:
            continue
        lines.append(f"constexpr VbcOperandDesc {array_name}[] = {{")
        for operand in op["operands"]:
            lines.append(
                "\t{{{}, VbcOperandRole::{}, VbcOperandKind::{}, {}, {}, {}}},".format(
                    _cpp_str(operand["name"]),
                    _pascal(operand["role"]),
                    _pascal(operand["kind"]),
                    _cpp_bool(operand["variadic"]),
                    _cpp_bool(operand["optional"]),
                    _cpp_bool(operand["cache"]),
                )
            )
        lines.append("};")
        lines.append("")
    lines.append("struct VbcOpDesc {")
    lines.append("\tconst char *name;")
    lines.append("\tbool emitted;")
    lines.append("\tbool may_park;")
    lines.append("\tbool yields;")
    lines.append("\tconst VbcOperandDesc *operands;")
    lines.append("\tint32_t operand_count;")
    lines.append("};")
    lines.append("")
    lines.append(f"constexpr VbcOpDesc kVbcOps[kVbcOpCount] = {{")
    for op in ops:
        operands_ref = f"kVbcOperands_{op['name']}" if op["operands"] else "nullptr"
        lines.append(
            "\t{{{}, {}, {}, {}, {}, {}}},".format(
                _cpp_str(op["name"]),
                _cpp_bool(op["emitted"]),
                _cpp_bool(op["may_park"]),
                _cpp_bool(op["yields"]),
                operands_ref,
                len(op["operands"]),
            )
        )
    lines.append("};")
    lines.append("")
    lines.append(
        "// The same digest `gen_vbc_ops.py --digest` prints. format.md §2.1 requires a reader to"
    )
    lines.append("// refuse a .vbc file stamped with any other -- this is what an engine bump changing")
    lines.append("// the op set is caught by.")
    lines.append(f"constexpr char kVbcOpsSchemaDigest[] = {_cpp_str(digest(schema))};")
    lines.append("")
    lines.append("} // namespace vbc")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--digest", action="store_true")
    parser.add_argument("--emit-cpp", metavar="PATH", help="write the decoder tables to this C++ header")
    args = parser.parse_args()
    schema = load()
    if args.digest:
        print(digest(schema))
        return 0
    errors = validate(schema)
    for error in errors:
        print(f"FAIL {error}")
    if errors:
        return 1
    if args.emit_cpp:
        out_path = pathlib.Path(args.emit_cpp)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(emit_cpp(schema), encoding="utf-8", newline="\n")
        print(f"wrote {out_path} ({len(schema['ops'])} ops)")
        return 0
    emitted = sum(1 for op in schema["ops"] if op["emitted"])
    print(f"ok {len(schema['ops'])} ops, {emitted} emitted, digest {digest(schema)[:12]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
