#!/usr/bin/env python3
"""Generates src/verse_keywords.h from the UE Verse compiler's own sources.

Reads VERSE_ENUMERATE_RESERVED_SYMBOLS(DECLARE_RESERVED_SYMBOL(...)) entries out of
uLang/Parser/ReservedSymbols.inl, keeps the plain-identifier spellings that are Reserved
or ReservedFuture, and reads the plain-identifier symbols out of the
`constexpr STokenInfo Tokens[] = { ... }` table in uLang/Parser/VerseGrammar.h --
ReservedSymbols.inl's own top-of-file comment says that table is where the words it does
not list (`if`, `else`, `var`, ...) live instead. EXTRA_KEYWORDS below is what is left over
after both: a seam for a word neither source lists, kept only with a comment saying why.

`--check` regenerates into memory and fails if it differs from the committed header --
docs/architecture-review.md item 4 step 5, so an engine drop that actually changed one of
these tables is caught rather than silently left stale.
"""

import argparse
import re
import sys
from pathlib import Path

IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

DECLARE_RE = re.compile(
    r'DECLARE_RESERVED_SYMBOL\(\s*'
    r'[A-Za-z0-9_]+\s*,\s*'
    r'u8"((?:[^"\\]|\\.)*)"\s*,\s*'
    r'EIsReservedSymbolResult::(\w+)'
)

KEPT_RESERVATIONS = {"Reserved", "ReservedFuture"}

RESERVED_SYMBOLS_PATH = "Engine/Source/Runtime/VerseCompiler/Public/uLang/Parser/ReservedSymbols.inl"
VERSE_GRAMMAR_PATH = "Engine/Source/Runtime/VerseCompiler/Public/uLang/Parser/VerseGrammar.h"

# The `constexpr STokenInfo Tokens[] = { ... };` table: each entry opens with `{`, whitespace,
# then its symbol as a `u8"..."` literal (the rest of the entry is precedence/associativity enums
# and a token-set reference, none of which is a quoted string) -- so the same shape that finds an
# entry's symbol also skips the four entries whose symbol is empty (unknown, end, NewLine, Alpha,
# Digit) and the operator/punctuation entries, which are not plain identifiers either.
GRAMMAR_TABLE_RE = re.compile(r"constexpr STokenInfo Tokens\[\] = \{(.*?)\n\};", re.S)
GRAMMAR_ENTRY_RE = re.compile(r'\{\s*u8"((?:[^"\\]|\\.)*)"')

# Words neither ReservedSymbols.inl nor VerseGrammar.h's token table names at all, kept only when
# there is a reason to write here rather than to find the word in one of those two files. Empty
# today: every word this used to carry -- the control-flow/declaration set, and the handful
# ReservedSymbols.inl's header comment says live in the grammar table -- turned out to already be
# in one of the two derived sources once GRAMMAR_KEYWORDS stopped being a hand transcription of it,
# which is itself the finding docs/architecture-review.md item 4 step 5 asked this file to surface.
EXTRA_KEYWORDS = []

CONTROL_FLOW_WORDS = [
    "branch", "break", "case", "defer", "else", "for", "if", "loop", "race",
    "return", "rush", "spawn", "sync", "then", "until",
]

HEADER_TEMPLATE = """#pragma once

// Generated by tools/gen_verse_keywords.py from the UE Verse compiler's ReservedSymbols.inl and
// VerseGrammar.h. Do not edit by hand.

namespace verse_keywords {{

inline constexpr const char *reserved_words[] = {{
{reserved_lines}
}};

inline constexpr const char *control_flow_words[] = {{
{control_flow_lines}
}};

}} // namespace verse_keywords
"""


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def parse_reserved_symbols(inl_path: Path):
    text = inl_path.read_text(encoding="utf-8")
    matches = DECLARE_RE.findall(text)
    parsed_count = len(matches)

    identifiers = set()
    for spelling, reservation in matches:
        if reservation not in KEPT_RESERVATIONS:
            continue
        if not IDENTIFIER_RE.match(spelling):
            continue
        identifiers.add(spelling)

    return parsed_count, identifiers


def parse_grammar_keywords(header_path: Path):
    """The plain-identifier symbols in VerseGrammar.h's token table -- `if`, `var`, `where`, and
    so on -- as (entries seen, identifiers kept). Raises if the table itself cannot be found, since
    that means the engine moved the table rather than that this file has nothing to report.
    """
    text = header_path.read_text(encoding="utf-8")
    table_match = GRAMMAR_TABLE_RE.search(text)
    if table_match is None:
        raise ValueError(f"could not find 'constexpr STokenInfo Tokens[]' in {header_path}")

    entries = GRAMMAR_ENTRY_RE.findall(table_match.group(1))
    parsed_count = len(entries)
    identifiers = {e for e in entries if IDENTIFIER_RE.match(e)}
    return parsed_count, identifiers


def format_entries(words) -> str:
    return "\n".join(f'\t"{w}",' for w in words)


def generate(engine_root: Path) -> tuple[str, str]:
    """Returns (header text, a one-line summary of what was parsed). Raises FileNotFoundError if
    either engine source file is missing, so a caller can tell "no engine checkout" apart from
    "the engine's own tables changed shape" (parse_grammar_keywords raises ValueError for that).
    """
    reserved_path = engine_root / RESERVED_SYMBOLS_PATH
    if not reserved_path.is_file():
        raise FileNotFoundError(reserved_path)
    grammar_path = engine_root / VERSE_GRAMMAR_PATH
    if not grammar_path.is_file():
        raise FileNotFoundError(grammar_path)

    parsed_count, identifiers = parse_reserved_symbols(reserved_path)
    grammar_parsed_count, grammar_keywords = parse_grammar_keywords(grammar_path)

    words = set(identifiers)
    extras_merged = 0
    for kw in EXTRA_KEYWORDS + sorted(grammar_keywords):
        if kw not in words:
            words.add(kw)
            extras_merged += 1

    final_words = sorted(words)

    header = HEADER_TEMPLATE.format(
        reserved_lines=format_entries(final_words),
        control_flow_lines=format_entries(CONTROL_FLOW_WORDS),
    )

    summary = (
        f"parsed {parsed_count} DECLARE_RESERVED_SYMBOL entries, {len(identifiers)} survived "
        f"the identifier/reservation filter, {grammar_parsed_count} grammar-table entries seen, "
        f"{len(grammar_keywords)} plain-identifier grammar keywords, "
        f"{extras_merged} extras merged, {len(final_words)} final reserved words"
    )
    return header, summary


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--engine-root",
        default=str(Path("../UnrealEngine")),
        help="Path to the UnrealEngine checkout (default: ../UnrealEngine relative to the repo root)",
    )
    parser.add_argument(
        "--out",
        default="src/verse_keywords.h",
        help="Output header path, relative to the repo root unless absolute (default: src/verse_keywords.h)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Regenerate into memory and fail if it differs from --out, instead of writing it",
    )
    args = parser.parse_args()

    root = repo_root()

    engine_root = Path(args.engine_root)
    if not engine_root.is_absolute():
        engine_root = (root / engine_root).resolve()

    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = root / out_path

    try:
        header, summary = generate(engine_root)
    except FileNotFoundError as e:
        print(f"error: could not find {e.filename or e}", file=sys.stderr)
        return 1
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1

    if args.check:
        if not out_path.is_file():
            print(f"[gen_verse_keywords] --check: {out_path} does not exist", file=sys.stderr)
            return 1
        committed = out_path.read_text(encoding="utf-8")
        if committed != header:
            print(f"[gen_verse_keywords] --check: {out_path} is stale -- {summary}", file=sys.stderr)
            print("[gen_verse_keywords] --check: run tools/gen_verse_keywords.py and commit the diff",
                  file=sys.stderr)
            return 1
        print(f"[gen_verse_keywords] --check: {out_path} matches -- {summary}")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header, encoding="utf-8", newline="\n")

    print(f"{summary} -> {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
