#!/usr/bin/env python3
"""Generates src/verse_keywords.h from the UE Verse compiler's ReservedSymbols.inl.

Reads VERSE_ENUMERATE_RESERVED_SYMBOLS(DECLARE_RESERVED_SYMBOL(...)) entries out of
uLang/Parser/ReservedSymbols.inl, keeps the plain-identifier spellings that are Reserved
or ReservedFuture, and merges in a fixed set of Verse-language keywords that
ReservedSymbols.inl deliberately excludes (see its top-of-file comment) because they
live in the parser's token table (uLang/Parser/VerseGrammar.h) instead.
"""

import argparse
import re
import sys
from pathlib import Path

IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

DECLARE_RE = re.compile(
    r'DECLARE_RESERVED_SYMBOL\(\s*'
    r'[A-Za-z0-9_]+\s*,\s*'
    r'u8"((?:[^"\\]|\\.)*)"\s*,\s*'
    r'EIsReservedSymbolResult::(\w+)'
)

KEPT_RESERVATIONS = {"Reserved", "ReservedFuture"}

# Verse-language keywords that ReservedSymbols.inl explicitly says live in the parser's
# token list instead (see its header comment), plus a few control-flow/declaration words
# not spelled out anywhere in ReservedSymbols.inl at all. Requested unconditionally by
# the task; duplicates against the parsed set are reported, not treated as errors.
EXTRA_KEYWORDS = [
    "and", "block", "break", "case", "class", "defer", "do", "else", "enum",
    "external", "for", "if", "import", "interface", "loop", "module", "not",
    "option", "or", "profile", "race", "return", "rush", "set", "spawn",
    "struct", "sync", "then", "until", "using", "var", "where",
]

# Plain-identifier keywords pulled from the `constexpr STokenInfo Tokens[] = { ... }`
# table in uLang/Parser/VerseGrammar.h (roughly lines 645-796 as of this writing). That
# table also holds operators/punctuation ("+", ":=", "<-", ...), which are excluded here
# the same way they are excluded from ReservedSymbols.inl. Words already covered by
# ReservedSymbols.inl or EXTRA_KEYWORDS above (and, at/as, break, do, if, in, is, not,
# of, or, over, return, set, then, to, until, var, when, where, while, with, yield, ...)
# are just duplicates of those and are reported, not re-added.
GRAMMAR_KEYWORDS = [
    "alias", "and", "at", "break", "catch", "const", "continue", "do", "else",
    "if", "in", "is", "live", "mutable", "next", "not", "of", "or", "over",
    "ref", "return", "set", "then", "to", "until", "when", "where", "while",
    "with", "yield", "var",
]

CONTROL_FLOW_WORDS = [
    "branch", "break", "case", "defer", "else", "for", "if", "loop", "race",
    "return", "rush", "spawn", "sync", "then", "until",
]

HEADER_TEMPLATE = """#pragma once

// Generated by tools/gen_verse_keywords.py from the UE Verse compiler's ReservedSymbols.inl.
// Do not edit by hand.

namespace verse_keywords {{

inline constexpr const char *reserved_words[] = {{
{reserved_lines}
}};

inline constexpr const char *control_flow_words[] = {{
{control_flow_lines}
}};

}} // namespace verse_keywords
"""


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def parse_reserved_symbols(inl_path: Path):
    text = inl_path.read_text(encoding="utf-8")
    matches = DECLARE_RE.findall(text)
    parsed_count = len(matches)

    identifiers = set()
    for spelling, reservation in matches:
        if reservation not in KEPT_RESERVATIONS:
            continue
        if not IDENTIFIER_RE.match(spelling):
            continue
        identifiers.add(spelling)

    return parsed_count, identifiers


def format_entries(words) -> str:
    return "\n".join(f'\t"{w}",' for w in words)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--engine-root",
        default=str(Path("../UnrealEngine")),
        help="Path to the UnrealEngine checkout (default: ../UnrealEngine relative to the repo root)",
    )
    parser.add_argument(
        "--out",
        default="src/verse_keywords.h",
        help="Output header path, relative to the repo root unless absolute (default: src/verse_keywords.h)",
    )
    args = parser.parse_args()

    root = repo_root()

    engine_root = Path(args.engine_root)
    if not engine_root.is_absolute():
        engine_root = (root / engine_root).resolve()

    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = root / out_path

    inl_path = (
        engine_root
        / "Engine/Source/Runtime/VerseCompiler/Public/uLang/Parser/ReservedSymbols.inl"
    )
    if not inl_path.is_file():
        print(f"error: could not find {inl_path}", file=sys.stderr)
        return 1

    parsed_count, identifiers = parse_reserved_symbols(inl_path)
    survived_count = len(identifiers)

    words = set(identifiers)
    extras_merged = 0
    for kw in EXTRA_KEYWORDS + GRAMMAR_KEYWORDS:
        if kw not in words:
            words.add(kw)
            extras_merged += 1

    final_words = sorted(words)

    header = HEADER_TEMPLATE.format(
        reserved_lines=format_entries(final_words),
        control_flow_lines=format_entries(CONTROL_FLOW_WORDS),
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header, encoding="utf-8", newline="\n")

    print(
        f"parsed {parsed_count} DECLARE_RESERVED_SYMBOL entries, "
        f"{survived_count} survived the identifier/reservation filter, "
        f"{extras_merged} extras merged, "
        f"{len(final_words)} final reserved words -> {out_path}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
