"""Generates host/Private/HostVbcOps.gen.h, the cooker's per-op encoder, from docs/web-vm/ops.json.

    python tools/gen_vbc_writer.py            # write the header
    python tools/gen_vbc_writer.py --check    # exit 1 if the header on disk is stale

One case per opcode, each naming the op struct's fields in the schema's order and calling the
encoder method that the operand's kind, variadic and optional flags select. Cache operands are
skipped, and an inline-cache opcode is written as the base op it was rewritten from (format.md
§5.1). The header also carries the schema digest the .vbc header is stamped with, so a writer
built from one ops.json cannot claim another.

This file is in the dirty room's half of the tree only through what it generates: it reads nothing
but ops.json, and the header it writes lives in host/Private.
"""

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import gen_vbc_ops  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "host" / "Private" / "HostVbcOps.gen.h"

STEMS = {
    "register": "Register",
    "value": "Value",
    "value_imm": "ValueImm",
    "label": "Label",
    "live_range": "LiveRange",
    "failure_context_id": "FailureContextId",
    "asset_path": "AssetPath",
    "bool": "Bool",
    "i32": "I32",
    "u32": "U32",
    "enum:ClassKind": "ClassKind",
    "enum:ClassFlags": "ClassFlags",
}

ROLES = {
    "use": "Use",
    "immediate": "Immediate",
    "unify_def": "UnifyDef",
    "clobber_def": "ClobberDef",
    "const": "Const",
    "jump": "Jump",
}

# The inline-cache forms and the op each is a rewrite of: SanitizeOpCodes' three groups.
IC_PREFIXES = (("NewObjectIC", "NewObject"), ("LoadFieldIC", "LoadField"), ("CreateFieldIC", "CreateField"))


def stem(kind):
    if kind.startswith("cell:"):
        return "Cell"
    if kind not in STEMS:
        raise SystemExit(f"gen_vbc_writer: no encoder for operand kind {kind}")
    return STEMS[kind]


def method(operand):
    name = stem(operand["kind"])
    if operand["variadic"]:
        name += "Range"
    if operand["optional"]:
        name = "Opt" + name
    return name


def base_of(op, by_name):
    if op["category"] != "inline_cache":
        return op
    for prefix, base in IC_PREFIXES:
        if op["name"].startswith(prefix):
            base_op = by_name[base]
            mine = [o["name"] for o in op["operands"] if not o["cache"]]
            theirs = [o["name"] for o in base_op["operands"] if not o["cache"]]
            if mine != theirs:
                raise SystemExit(f"gen_vbc_writer: {op['name']} does not carry {base}'s operands")
            return base_op
    raise SystemExit(f"gen_vbc_writer: inline-cache op {op['name']} has no known base op")


def render(schema):
    ops = schema["ops"]
    by_name = {op["name"]: op for op in ops}
    digest = gen_vbc_ops.digest(schema)

    out = []
    w = out.append
    w("// Copyright Epic Games, Inc. All Rights Reserved.")
    w("#pragma once")
    w("")
    w("// Generated by tools/gen_vbc_writer.py from docs/web-vm/ops.json. Do not edit by hand.")
    w("//")
    w("// VbcEncodeOp calls one encoder method per operand the schema lists for the op, in the schema's")
    w("// order, skipping cache operands. The method is chosen by the operand's kind, then `Range` when")
    w("// it is variadic and an `Opt` prefix when it is optional; every call also carries the role.")
    w("")
    w('#include "VerseVM/VVMBytecodesAndCaptures.h"')
    w("")
    w("namespace GodotVerse::Vbc {")
    w("")
    w(f'inline constexpr const char* OpSchemaDigest = "{digest}";')
    w(f"inline constexpr uint32 OpCount = {len(ops)};")
    w("")
    w("enum class ERole : uint8")
    w("{")
    for role in ROLES.values():
        w(f"\t{role},")
    w("};")
    w("")
    w(f"static_assert(static_cast<uint32>(Verse::EOpcode::OpcodeCount) == {len(ops)}, "
      '"the engine\'s op set is not the one ops.json describes");')
    for op in ops:
        w(f"static_assert(static_cast<uint32>(Verse::EOpcode::{op['name']}) == {op['number']});")
    w("")
    w("inline constexpr const char* OpNames[OpCount] = {")
    for op in ops:
        w(f'\t"{op["name"]}",')
    w("};")
    w("")
    w("inline constexpr bool OpMayPark[OpCount] = {")
    for op in ops:
        w(f"\t{'true' if op['may_park'] else 'false'}, // {op['name']}")
    w("};")
    w("")
    w("/// The op's size in the stream, which is where the next op starts. Zero for an opcode the")
    w("/// schema does not have.")
    w("AUTORTFM_DISABLE inline uint32 OpSize(const Verse::FOp& Op)")
    w("{")
    w("\tswitch (Op.Opcode)")
    w("\t{")
    for op in ops:
        w(f"\t\tcase Verse::EOpcode::{op['name']}:")
        w(f"\t\t\treturn sizeof(Verse::FOp{op['name']});")
    w("\t\tdefault:")
    w("\t\t\treturn 0;")
    w("\t}")
    w("}")
    w("")
    w("template <typename TEncoder>")
    w("AUTORTFM_DISABLE void EncodeOp(TEncoder& E, Verse::FOp& Op)")
    w("{")
    w("\tswitch (Op.Opcode)")
    w("\t{")
    for op in ops:
        base = base_of(op, by_name)
        w(f"\t\tcase Verse::EOpcode::{op['name']}:")
        w("\t\t{")
        operands = [o for o in base["operands"] if not o["cache"]]
        if operands:
            w(f"\t\t\tVerse::FOp{op['name']}& O = static_cast<Verse::FOp{op['name']}&>(Op);")
        suffix = f" // written as {base['name']}" if base is not op else ""
        w(f"\t\t\tE.Opcode({base['number']});{suffix}")
        for operand in operands:
            w(f"\t\t\tE.{method(operand)}(O.{operand['name']}, ERole::{ROLES[operand['role']]});")
        w("\t\t\treturn;")
        w("\t\t}")
    w("\t\tdefault:")
    w("\t\t\tbreak;")
    w("\t}")
    w("\tE.UnknownOpcode(Op);")
    w("}")
    w("")
    w("} // namespace GodotVerse::Vbc")
    w("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = gen_vbc_ops.load()
    errors = gen_vbc_ops.validate(schema)
    if errors:
        for error in errors:
            print(f"FAIL {error}")
        return 1
    text = render(schema)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is stale; run tools/gen_vbc_writer.py")
            return 1
        print(f"{OUT} is current")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
