#pragma once

// Generated by tools/gen_verse_api.py from godot-cpp/gdextension/extension_api.json.
// Do not edit.

namespace verse_api {

struct class_mapping {
	const char *godot_name;
	const char *verse_name;
};

inline constexpr class_mapping classes[] = {
	{ "CanvasItem", "godot_canvas_item" },
	{ "Node", "godot_node" },
	{ "Node2D", "godot_node2d" },
};

} // namespace verse_api
