#pragma once

// Generated by tools/gen_verse_api.py from godot-cpp/gdextension/extension_api.json
// (Godot Engine v4.6.stable.official). Do not edit by hand.
//
// Maps each Godot class this bridge emits a Verse class for to that class's name, so the
// Godot side (VerseScriptLanguage::_make_template) can turn a node's Godot class into the
// Verse class it should subclass without re-deriving gen_verse_api.py's name transform.
// A Godot class that was not emitted (see GodotClasses.native.verse's coverage report) is
// absent here; the caller walks ClassDB::get_parent_class until it finds one that is.

namespace verse_api {

struct class_mapping {
	const char *godot_name;
	const char *verse_name;
};

inline constexpr class_mapping classes[] = {
	{ "AnimatedSprite2D", "animated_sprite2d" },
	{ "AnimationMixer", "animation_mixer" },
	{ "AnimationPlayer", "animation_player" },
	{ "Area2D", "area2d" },
	{ "Area3D", "area3d" },
	{ "AudioStreamPlayer", "audio_stream_player" },
	{ "AudioStreamPlayer2D", "audio_stream_player2d" },
	{ "AudioStreamPlayer3D", "audio_stream_player3d" },
	{ "BaseButton", "base_button" },
	{ "BoxContainer", "box_container" },
	{ "Button", "button" },
	{ "Camera2D", "camera2d" },
	{ "Camera3D", "camera3d" },
	{ "CanvasItem", "canvas_item" },
	{ "CanvasLayer", "canvas_layer" },
	{ "CharacterBody2D", "character_body2d" },
	{ "CharacterBody3D", "character_body3d" },
	{ "CollisionObject2D", "collision_object2d" },
	{ "CollisionObject3D", "collision_object3d" },
	{ "CollisionShape2D", "collision_shape2d" },
	{ "CollisionShape3D", "collision_shape3d" },
	{ "Container", "container" },
	{ "Control", "control" },
	{ "DirectionalLight2D", "directional_light2d" },
	{ "DirectionalLight3D", "directional_light3d" },
	{ "Engine", "engine" },
	{ "GeometryInstance3D", "geometry_instance3d" },
	{ "GridContainer", "grid_container" },
	{ "HBoxContainer", "h_box_container" },
	{ "Input", "input" },
	{ "Label", "label" },
	{ "Light2D", "light2d" },
	{ "Light3D", "light3d" },
	{ "LineEdit", "line_edit" },
	{ "MainLoop", "main_loop" },
	{ "MeshInstance3D", "mesh_instance3d" },
	{ "Node", "node" },
	{ "Node2D", "node2d" },
	{ "Node3D", "node3d" },
	{ "OmniLight3D", "omni_light3d" },
	{ "PackedScene", "packed_scene" },
	{ "Panel", "panel" },
	{ "PanelContainer", "panel_container" },
	{ "PhysicsBody2D", "physics_body2d" },
	{ "PhysicsBody3D", "physics_body3d" },
	{ "PointLight2D", "point_light2d" },
	{ "ProgressBar", "progress_bar" },
	{ "RandomNumberGenerator", "random_number_generator" },
	{ "Range", "range" },
	{ "RefCounted", "ref_counted" },
	{ "Resource", "resource" },
	{ "RichTextLabel", "rich_text_label" },
	{ "RigidBody2D", "rigid_body2d" },
	{ "RigidBody3D", "rigid_body3d" },
	{ "SceneTree", "scene_tree" },
	{ "SpotLight3D", "spot_light3d" },
	{ "Sprite2D", "sprite2d" },
	{ "Sprite3D", "sprite3d" },
	{ "SpriteBase3D", "sprite_base3d" },
	{ "StaticBody2D", "static_body2d" },
	{ "StaticBody3D", "static_body3d" },
	{ "TextEdit", "text_edit" },
	{ "Texture", "texture" },
	{ "Texture2D", "texture2d" },
	{ "TileMap", "tile_map" },
	{ "Time", "time" },
	{ "Timer", "timer" },
	{ "Tween", "tween" },
	{ "VBoxContainer", "v_box_container" },
	{ "Viewport", "viewport" },
	{ "VisualInstance3D", "visual_instance3d" },
	{ "Window", "window" },
};

} // namespace verse_api
