#pragma once

// Generated by tools/gen_verse_api.py from godot-cpp/gdextension/extension_api.json
// (Godot Engine v4.6.stable.official). Do not edit by hand.
//
// Maps each Godot class this bridge emits a Verse class for to that class's name, so the
// Godot side (VerseScriptLanguage::_make_template) can turn a node's Godot class into the
// Verse class it should subclass without re-deriving gen_verse_api.py's name transform.
// A Godot class that was not emitted (see GodotClasses.native.verse's coverage report) is
// absent here; the caller walks ClassDB::get_parent_class until it finds one that is.

namespace verse_api {

struct class_mapping {
	const char *godot_name;
	const char *verse_name;
};

inline constexpr class_mapping classes[] = {
	{ "AnimatedSprite2D", "godot_animated_sprite2d" },
	{ "AnimationMixer", "godot_animation_mixer" },
	{ "AnimationPlayer", "godot_animation_player" },
	{ "Area2D", "godot_area2d" },
	{ "Area3D", "godot_area3d" },
	{ "AudioStreamPlayer", "godot_audio_stream_player" },
	{ "AudioStreamPlayer2D", "godot_audio_stream_player2d" },
	{ "AudioStreamPlayer3D", "godot_audio_stream_player3d" },
	{ "BaseButton", "godot_base_button" },
	{ "BoxContainer", "godot_box_container" },
	{ "Button", "godot_button" },
	{ "Camera2D", "godot_camera2d" },
	{ "Camera3D", "godot_camera3d" },
	{ "CanvasItem", "godot_canvas_item" },
	{ "CanvasLayer", "godot_canvas_layer" },
	{ "CharacterBody2D", "godot_character_body2d" },
	{ "CharacterBody3D", "godot_character_body3d" },
	{ "CollisionObject2D", "godot_collision_object2d" },
	{ "CollisionObject3D", "godot_collision_object3d" },
	{ "CollisionShape2D", "godot_collision_shape2d" },
	{ "CollisionShape3D", "godot_collision_shape3d" },
	{ "Container", "godot_container" },
	{ "Control", "godot_control" },
	{ "DirectionalLight2D", "godot_directional_light2d" },
	{ "DirectionalLight3D", "godot_directional_light3d" },
	{ "Engine", "godot_engine" },
	{ "GeometryInstance3D", "godot_geometry_instance3d" },
	{ "GridContainer", "godot_grid_container" },
	{ "HBoxContainer", "godot_h_box_container" },
	{ "Input", "godot_input" },
	{ "Label", "godot_label" },
	{ "Light2D", "godot_light2d" },
	{ "Light3D", "godot_light3d" },
	{ "LineEdit", "godot_line_edit" },
	{ "MainLoop", "godot_main_loop" },
	{ "MeshInstance3D", "godot_mesh_instance3d" },
	{ "Node", "godot_node" },
	{ "Node2D", "godot_node2d" },
	{ "Node3D", "godot_node3d" },
	{ "OmniLight3D", "godot_omni_light3d" },
	{ "PackedScene", "godot_packed_scene" },
	{ "Panel", "godot_panel" },
	{ "PanelContainer", "godot_panel_container" },
	{ "PhysicsBody2D", "godot_physics_body2d" },
	{ "PhysicsBody3D", "godot_physics_body3d" },
	{ "PointLight2D", "godot_point_light2d" },
	{ "ProgressBar", "godot_progress_bar" },
	{ "RandomNumberGenerator", "godot_random_number_generator" },
	{ "Range", "godot_range" },
	{ "RefCounted", "godot_ref_counted" },
	{ "Resource", "godot_resource" },
	{ "RichTextLabel", "godot_rich_text_label" },
	{ "RigidBody2D", "godot_rigid_body2d" },
	{ "RigidBody3D", "godot_rigid_body3d" },
	{ "SceneTree", "godot_scene_tree" },
	{ "SpotLight3D", "godot_spot_light3d" },
	{ "Sprite2D", "godot_sprite2d" },
	{ "Sprite3D", "godot_sprite3d" },
	{ "SpriteBase3D", "godot_sprite_base3d" },
	{ "StaticBody2D", "godot_static_body2d" },
	{ "StaticBody3D", "godot_static_body3d" },
	{ "TextEdit", "godot_text_edit" },
	{ "Texture", "godot_texture" },
	{ "Texture2D", "godot_texture2d" },
	{ "TileMap", "godot_tile_map" },
	{ "Time", "godot_time" },
	{ "Timer", "godot_timer" },
	{ "Tween", "godot_tween" },
	{ "VBoxContainer", "godot_v_box_container" },
	{ "Viewport", "godot_viewport" },
	{ "VisualInstance3D", "godot_visual_instance3d" },
	{ "Window", "godot_window" },
};

} // namespace verse_api
